### ISSUE TITLE
Test environment

### ISSUE THREAD

**Issue by dhilt** [dhilt/dharmadict#10]
Add test environment to the project.

**Comment by dhilt** [comment]
@BitDen Я написал первые пробные тесты и сделал мерж в текущий бранч. Взгляни, пожалуйста! Пока я буду думать, как заводить тестового пользователя и тестовые данные.

**Comment by BitDen** [comment]
@dhilt Пока что мало понятно что и как работает, но как закончу с termsControllers, начну разбираться и тоже может пытаться на что-либо тест написать.

**Comment by dhilt** [comment]
@BitDen Не торопись с тестами, я просто хочу, чтобы ты был в курсе. Я сам напишу первые спеки, тебе останется только подхватить это дело. Сейчас главное закончить рефакторинг сервера. Я буду сливаться с активным бранчем, поскольку тесты требуют небольших модификаций по коду (в частности, ты мог заметить `module.exports = app` и ветвление в logger.js).

**Comment by dhilt** [comment]
@BitDen Нерешенными осталось несколько вопросов.

 - Почему нужна задержка после выполнения изменений в БД? Я хочу чтобы следующий тест видел результаты предыдущего без задержки! для тестирования мутаций в БД это принципиальный момент, иначе мы очень скоро погрязнем в таймаутах.

- Стоит ли оптимизировать логины? Не залогиниться ли сразу обоими пользователями, а в последующие спеки выдавать только токены?

 - И т.п..

Посмотри, пожалуйста, на первый вопрос, он очень важен.

**Comment by dhilt** [comment]
@BitDen Посмотри еще вопрос с задержкой из предыдущего комментария. Я вношу изменение в эластик-документ и хочу чтобы следующий запрос учитывал это изменение сразу же, без задержек. 

Как воспроизвести проблему? Берешь createUserSpec.js, убриаешь там два таймаута (по 1000 миллисекунд) на создание 2 пользователей и видишь, как падает тест "should not create the same (by login) user".

**Comment by BitDen** [comment]
@dhilt Да, я уже пробовал вчера. Учитывая мое пока что слабоватое понимание этих библиотек для тестирования, вряд ли смогу добраться до причины. Но я пробую.

**Comment by dhilt** [comment]
@BitDen Не трать больше 2-3 часов, переходи, если не будет движения, к проблеме русскоязычного поиска.

**Comment by BitDen** [comment]
@dhilt В общем наткнулся на статьи вроде этой: https://zaiste.net/posts/modern_node_js_async_await_based_testing_with_mocha_chai/ и начал пытаться с помощью `after(() => {...})` и `afterEach(() => {...})` перенести попытки повторного создания пользователя и админа в конец очереди (и вдобавок разместив afterEach на deleteUserSpec.js). Примерно так выглядел код на createUserSpec:
```
after(() => {
  it('should not create the same (by login) user', (done) => {
    usersController.create(testAdmin)
      .then(result => done(new Error('User was created')))
      .catch(error => {
        assert.equal(error.text, 'Login not unique');
        done();
      })
  });

  it('should not create the same (by id) user', (done) => {
    let user = Object.assign({}, testAdmin);
    user.login = user.login + 'NEW';
    usersController.create(user)
      .then(result => done(new Error('User was created')))
      .catch(error => {
        assert.equal(error.text, 'Id not unique');
        done();
      })
  });
});
```
и такой неожиданный результат пришел:

![screenshot from 2017-09-10 23-21-33](https://user-images.githubusercontent.com/26064824/30250672-3f2466d6-9685-11e7-99d3-c614c4cdc8d3.png)

**Comment by BitDen** [comment]
@dhilt Может как-то внутри describe сделать локальный promise, даже и не знаю.

**Comment by BitDen** [comment]
Стоит сказать, однажды случайно желанный результат взял да случился:
![screenshot from 2017-09-10 23-21-33](https://user-images.githubusercontent.com/26064824/30250755-9f2c308a-9686-11e7-87d8-9cde67e21899.png)

И как я понял все дело в асинхронности (больше такого не повторялось), и вот думаю что нужен promise или некие хитрые функции after и afterEach, которые пока не до конца понял.

**Comment by BitDen** [comment]
@dhilt А пока наверное стоит доделать updateTermSpec все же, а затем и к задаче с русскоязычным поиском.

**Comment by dhilt** [comment]
@BitDen Ты можешь закомитить промежуточный результат по асинхронным тестам в некий новый бранч, я посомтрю. Я уже начал работу с dev, даже сделал пару комитов, ты можешь посмотреть и продолжить эту работу. Но русскоязычный писк очень важен.

**Comment by BitDen** [comment]
@dhilt Да никакого результата ведь нет, просто последние два `it` на createUserSpec обрамил в колбэк функции `after(() => {...})` и все безуспешно.
А как там с адекватным клонированием объекта testTermTranslation, есть успехи?

**Comment by dhilt** [comment]
@BitDen Итак, я дольше писал, чем реально фиксил это issue. Я задал вопрос гуглу "elasticsearch immediate request after update". Я перешел на документацию https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html и увидел опцию refresh. Все.

**Comment by BitDen** [comment]
@dhilt Вот так вот плоховатое знание английского тормозит)
