### ISSUE TITLE
Get a snapshot with actual users

### ISSUE THREAD

**Issue by dhilt** [dhilt/dharmadict#12]
В результате работы над добавлением пользователей в эластик, мы должны получить обновленный дамп БД. Нужно взять исходное состояние БД, накатить на него пользователей и сделать снапшот. Перед тем как начисто добавлять пользователей, необходимо задать правильный mapping для типа users. По этому поводу см. issue https://github.com/dhilt/dharmadict/issues/11.

Пошли этот снапшот мне, я попробую его восстановить локально. Это будет новая отправная точка при разворачивании проекта в production.

**Comment by BitDen** [comment]
[my_backup.zip](https://github.com/dhilt/dharmadict/files/1284656/my_backup.zip)

**Comment by BitDen** [comment]
@dhilt Вроде как готово.

**Comment by dhilt** [comment]
@BitDen Хорошо, я буду сегодня смотреть!

Мне выдали доступ к хостингу, там чистая ОС. Давай попробуем последний эластик! Обновись локально, 5.5.2 сейчас последняя версия, и посмотри, все ли работает как надо, нет ли критичных изменений в их api? встает ли наш snapshot? срастается ли elasticClient? проходят ли базовые запросы через приложение? Если все пройдет гладко (а мне кажется, что проблем не должно быть, тем более, что мы пользуемся очень незначительным функционалом), то я буду ставить на сервере последнюю версию.

**Comment by dhilt** [comment]
Снапшот прекрасно работает, я очень рад, что мы довели процедуру сохранения/восстановления данных до приемлемого вида! Надо пощупать последний эластик и я займусь production.

**Comment by BitDen** [comment]
@dhilt Ну, я собственно когда делал какой-то функционал, связанный с эластиком, смотрел в документации версии 5.5, думаю все должно быть славно. Сейчас обновлюсь, и буду пробовать - если что странное появится, напишу.

**Comment by BitDen** [comment]
@dhilt Со снапшотами все в порядке, создаются, восстанавливаются. Только у меня не вышло восстановиться от снапшота, сделанного на версии 1.7.2 - но скорее всего тут замешана моя извечная борьба с правами на папки и проблема где-то там, в недопонимании операционной системы.

**Comment by dhilt** [comment]
@BitDen Нам нужно получить полный снапшот (исходные данные по переводам + переводчики с правильным мапированием), восстанавливаемый на новом эластике, удостовериться, что приложение работает как надо (скоро это будут делать за нас тесты, которыми я занимаюсь сейчас) и можно будет разворачивать prod.

**Comment by BitDen** [comment]
@dhilt Ложная тревога со снапшотом, сейчас еще раз попробовал на новом эластике и все получилось.

**Comment by dhilt** [comment]
@BitDen Я поставил последний эластик на сервер, запустил его, настроил репозиторий для снапшотов. Но не смог сделать POST твоего снапшота.

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_state_exception",
        "reason" : "unsupported compression: index was created before v2.0.0.beta1 and wasn't upgraded?"
      }
    ],
    "type" : "illegal_state_exception",
    "reason" : "unsupported compression: index was created before v2.0.0.beta1 and wasn't upgraded?"
  },
  "status" : 500
}
```

Исходя из https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-upgrade.html, это невозможно сделать без дополнительных операций, связанных с вервисей 2.3. Уверен ли ты, что твоя система работает с 5 эластиком (выполни curl -XGET 'localhost:9200')? Если да, то может быть ты пересоздавал все данные через старую процедуру на гранте? Так или иначе, но сервер хочет снапшот, сделанный на 5 эластике и тот снапшот, который ты прикреплял к этому issue на сервере не работает. 

Убедись, что у тебя работает 5 эластик, что индекс наполнен данными и приложение их видит, после этого сделай новый снапшот и погли его мне.

Еслибудешь пересоздавать с нуля, посмотри, я подправил маппинг для users: https://github.com/dhilt/dharmadict/issues/11.

**Comment by BitDen** [comment]
@dhilt К сожалению вышла путаница и похоже я оставался на старой версии. Сейчас пробую версию 5.5.2, и данные из старого репозитория не запихиваются в базу данных, сыпятся ошибки и эластик падает.
Если не вводить строки, показанные ниже, в /etc/elasticsearch/elasticsearch.yml, то база данных наполнится всеми доступными 172 терминами, но без переводов, комментариев и авторов. Наверное это Terms.csv только удачно проходит...

**Comment by dhilt** [comment]
@BitDen Да, эти параметры нужны для того, чтобы корректно заработал импорт из грант-задачи. Вот это конкретно место

```
script: "if (ctx._source.containsKey('translations')) {def idx = ctx._source.translations.findIndexOf {t -> t.translatorId == authorId}; if (idx == -1) ctx._source.translations += translation; else ctx._source.translations[idx] = translation;} else {ctx._source.translations = [translation]}"
```

У меня сервер не запускал 5 эластик, пока я не убрал 2 параметра script.indexed и script.engine.groovy.inline.aggs. Возможно есть альтернативные параметры для 5 версии. Возможно скрипт не валиден для 5 версии. Это можно исследовать.

Еще можно попробовать попробовать путь через с elasticsearch v2.3.

**Comment by BitDen** [comment]
@dhilt Попробовать путь через v2.3 - это значит на сервере будет стоять эластик версии 2.3 или же это значит порассматривать документацию этой версии и поискать места, где функционал версии 1.7.2 потерял свою значимость или же изменился?

**Comment by dhilt** [comment]
@BitDen Как я понял из ссылки выше, можно пергнать индекс из 1.7 с 2.3, а потом поставить 5.5 и перегнать из 2.3 в 5.5. Прямого пути 1.7 -> 5.5 нет.

**Comment by BitDen** [comment]
@dhilt Перегнать как именно? Делая снапшоты? Допустим сделать на 1.7, затем восстановиться на 2.3, затем еще разок сделать снапшот, и потом восстановиться на 5.5?

**Comment by dhilt** [comment]
@BitDen Примерно. Посмотри в https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-upgrade.html, там описана процедура.

**Comment by BitDen** [comment]
@dhilt Хорошо, сейчас буду пробовать.

**Comment by BitDen** [comment]
[my_backup.zip](https://github.com/dhilt/dharmadict/files/1288504/my_backup.zip)

**Comment by BitDen** [comment]
@dhilt Очень долго провозился что-то, но вроде готово.

**Comment by BitDen** [comment]
В конфиг файле я прописывал только `path.repo ['/home/den/backups']`, без других четырех строк.
И если с первого раза не получится восстановиться и вылетит ошибка, говорящая якобы репозиторий не найден или что-то вроде того, можно попробовать следующие команды:
```
sudo chown elasticsearch:elasticsearch /home/den/backups/my_backup
curl -XPUT 'http://localhost:9200/_snapshot/my_backup?pretty' -H 'Content-Type: application/json' -d '{"type": "fs", "settings": {"location": "my_backup", "compress": true}}'
```

**Comment by BitDen** [comment]
@dhilt И вопрос насчет документа `users` - пользователи с ролью переводчика все еще должны иметь поле `language: rus`? Если да, то все хорошо, это дело имеется.

**Comment by dhilt** [comment]
@BitDen Да, language пусть остается. Сейчас буду пробовать.

**Comment by dhilt** [comment]
@BitDen Снапшот встал, отличная работа!

**Comment by dhilt** [comment]
Это уже на сервере:

![dharmadict ru_tests](https://user-images.githubusercontent.com/4365660/30222235-322ad60c-94cf-11e7-9cd2-fce4d257149d.png)

Как веб-приложение поднять, я пока не совсем понимаю. Послал запрос.

**Comment by BitDen** [comment]
@dhilt Здорово. Надо бы еще проверить все ли удачно получилось с mapping у пользователей. Эластик новой версии в properties похоже не все свойства показывает. Вот примерно что показал, после того как задал mapping:
![screenshot from 2017-09-08 23-58-30](https://user-images.githubusercontent.com/26064824/30222279-4280e206-94f9-11e7-8b74-4db17aa02993.png)

**Comment by BitDen** [comment]
@dhilt Даже и не могу представить в чем может быть проблема там. Из своего небольшего опыта воевания на linux'е могу предположить что может дело в правах на разные файлы, мне иногда приходиться жонглировать правами `root`, `den`(username) и `elasticsearch`...

**Comment by dhilt** [comment]
@BitDen Это новый api, с этим нет проблем, просто это надо учитывать:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html

**Comment by dhilt** [comment]
@BitDen Я имплементировал db-reset для 5 эластика. Большую часть работ я сделал до того, как ты победил снапшот. Я был настолько неуверен в успехе со снапшотом, что решил параллельно попробовать путь прямого экспорта данных. И по-моему я тоже преуспел. Проверь у себя, пожалуйста:

 - забери бранч db (https://github.com/dhilt/dharmadict/tree/db)
 - обнови полностью сервер (/prod/node_modules, npm install, я повысил версию эластик-клиента), 
 - проследи, чтобы в elasticsearch.yml было два параметра script.inline: on и script.engine.groovy.inline.aggs: on,
 - выполни npm ru db-reset

**Comment by BitDen** [comment]
@dhilt Ничего себе скорость, столько написали за небольшое время, круто.
Вот что показала консоль:
```
den@den-VirtualBox:~/projects/dharmadict$ npm run db-reset

> dharmadict-forntend@0.0.1 db-reset /home/den/projects/dharmadict
> node prod/db/reset.js

Elasticsearch INFO: 2017-09-08T21:34:13Z
  Adding connection to http://localhost:9200/

DB reset scripts running

==== Delete dharmadict index
++++ Delete dharmadict index... Success! No index found...

==== Create dharmadict index
---- Create dharmadict index... Fail! 
{ Error: Bad Request
    at respond (/home/den/projects/dharmadict/prod/node_modules/elasticsearch/src/lib/transport.js:293:15)
    at checkRespForFailure (/home/den/projects/dharmadict/prod/node_modules/elasticsearch/src/lib/transport.js:252:7)
    at HttpConnector.<anonymous> (/home/den/projects/dharmadict/prod/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
    at IncomingMessage.wrapper (/home/den/projects/dharmadict/prod/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  status: 400,
  displayName: 'BadRequest',
  message: 'Bad Request',
  body: 'No handler found for uri [/dharmadict] and method [POST]' }

==== Add terms
++++ Add terms... Success! really

==== Add users
++++ Add users... Success! 8 users have been added

==== Add translations
MK.csv was processed successfully
AKT.csv was processed successfully
ZAG.csv was processed successfully
DON.csv was processed successfully
HOP.csv was processed successfully
BRZ.csv was processed successfully
++++ Add translations... Success! really
```

Пользователи занеслись, термины тоже, но переводы похоже нет:

![screenshot from 2017-09-09 05-20-06](https://user-images.githubusercontent.com/26064824/30232195-2d97c058-9521-11e7-8eb1-d4724a937cb9.png)

**Comment by BitDen** [comment]
Пробовал дважды, с уже существующим индексом dharmadict в эластике, и переустановив эластик заново, то есть с пустым эластиком.

**Comment by dhilt** [comment]
@BitDen Мне на сервере пришлось подрезать память JVM с 2Гб до 1, в 5 эластике прописано 2 по умолчанию, а на хостинге нет столько... Твой лог почти адекватен. Я вижу проблемы с созданием индекса, но это некритично (маппинг мог не примениться). Видно, что все проходит. 

Дело в том, что я не закомитил указание нужного api для elasticsearchClient, а в мапировании users я использовал новые правила (keyword type). Заберись сейчас с бранча db и прогони npm tun db-reset.

**Comment by BitDen** [comment]
@dhilt Прогнал, результат тот же.

**Comment by dhilt** [comment]
@BitDen У меня локально через вагрант и на сервере с чистой убунтой npm db-reset проходит уже без ошибок. Код синхронизован с бранчем db. Ты точно видишь у себя https://github.com/dhilt/dharmadict/blob/db/prod/db/config.js#L5?

И еще лог "++++ Delete dharmadict index... Success! No index found..." говорит о том, что такого индекса нет.

Попробуй также измени индекс, напиши в конфиге "dharmadict-test" (https://github.com/dhilt/dharmadict/blob/db/prod/db/config.js#L7).

**Comment by BitDen** [comment]
@dhilt Да, у меня все на месте и npm install проделал в двух местах. Результат с `test-dharmadict` такой:
```
den@den-VirtualBox:~/projects/dharmadict$ npm run db-reset

> dharmadict-forntend@0.0.1 db-reset /home/den/projects/dharmadict
> node prod/db/reset.js

Elasticsearch INFO: 2017-09-08T22:46:56Z
  Adding connection to http://localhost:9200/

DB reset scripts running

==== Delete test-dharmadict index
++++ Delete test-dharmadict index... Success! 

==== Create test-dharmadict index
++++ Create test-dharmadict index... Success! 

==== Add terms
++++ Add terms... Success! really

==== Add users
++++ Add users... Success! 8 users have been added

==== Add translations
MK.csv was processed successfully
AKT.csv was processed successfully
ZAG.csv was processed successfully
DON.csv was processed successfully
HOP.csv was processed successfully
BRZ.csv was processed successfully
++++ Add translations... Success! really
```

Термины все создаются, но переводов нет. Сейчас со снапшота восстановлюсь и прикреплю скриншот как вроде бы должны выглядеть данные...

**Comment by BitDen** [comment]
![screenshot from 2017-09-09 06-50-44](https://user-images.githubusercontent.com/26064824/30233894-417d4bce-952b-11e7-9244-0add9e7d0f55.png)

**Comment by BitDen** [comment]
@dhilt У вас это все на месте? И может пробовали еще и сам проект запустить, что обычно на localhost:5000 был, были ли там переводы?

**Comment by dhilt** [comment]
@BitDen Я сейчас в процессе запуска через приложение...

**Comment by dhilt** [comment]
@BitDen Да, с переводами и у меня, кажется, не чисто. Но я вижу, что у тебя индекс встает уже как надо.

**Comment by dhilt** [comment]
@BitDen Приложение не хочет работать с новым эластик-клиентом. Эластик выдает после первого обращения:

```
> node prod/server.js

Elasticsearch INFO: 2017-09-08T22:58:48Z
  Adding connection to http://localhost:9200/

2017-09-08T22:58:48.711Z - info: Listening on port 3000...
2017-09-08T22:58:51.694Z - info: Find user by login admin
Elasticsearch ERROR: 2017-09-08T22:58:51Z
  Error: Request error, retrying
  POST http://localhost:9200/dharmadict/users/_search => read ECONNRESET
      at Log.error (D:\github\dhilt\dharmadict\prod\node_modules\elasticsearch\src\lib\log.js:225:56)
      at checkRespForFailure (D:\github\dhilt\dharmadict\prod\node_modules\elasticsearch\src\lib\transport.js:258:18)
      at HttpConnector.<anonymous> (D:\github\dhilt\dharmadict\prod\node_modules\elasticsearch\src\lib\connectors\http.js:157:7)
      at ClientRequest.bound (D:\github\dhilt\dharmadict\prod\node_modules\lodash\dist\lodash.js:729:21)
      at emitOne (events.js:115:13)
      at ClientRequest.emit (events.js:210:7)
      at Socket.socketErrorListener (_http_client.js:400:9)
      at emitOne (events.js:115:13)
      at Socket.emit (events.js:210:7)
      at emitErrorNT (internal/streams/destroy.js:62:8)
```

Через тесты при этом тот же эластик-клиент (тесты не порождают отдельного инстанса, все общение идет через сервер) работает нормально. Разница только в том, что в 1 случае запрос инициируется по http, а во втором через chai-http (npm пакет для эмуляции запросов к серверу).

Попробуй тоже запусти у себя приложение и поисследуй эту проблему.

**Comment by BitDen** [comment]
@dhilt Хмм, а у меня все в порядке. И тесты, и само приложение. Слова находятся, пользователи логинятся.

**Comment by dhilt** [comment]
@BitDen Похоже, у меня где-то повисли коннекции...

**Comment by dhilt** [comment]
@BitDen Я пофиксил процедуру импорта терминов, посмотри, пожалуйста, бранч. И можно переходить к задаче о termsController.update.

**Comment by BitDen** [comment]
@dhilt Посмотрел. Теперь все работает, все переводы и пользователи на месте.

**Comment by BitDen** [comment]
@dhilt Хмм, у меня вот кстати тоже вылетела ошибка, как и у вас на скриншоте. Просмотрел бранч, написал комментарий выше и далее уже начал возвращаться на бранч 'translator-page', удалил оба node_modules, переинсталлировал (так как на бранчах разные npm-пакеты эластика) и только написал npm start, как увидел ту же самую ошибку `npm update check failed`. И как-то особо не раздумывая попробовал сходу написать совет из ошибки аля `sudo chown -R ...`. Иии операционная система вполне себе удачно полностью рухнула. При дальнейшем запуске, вылетало окно как на первом скриншоте (как я понял появились некие повреждения в файловой системе) и следуя простому совету https://askubuntu.com/questions/651577/dev-sda1-inodes-that-were-part-of-a-corrupted-orphan-linked-list-found вбил `fsck /dev/sda<number>` и всюду на вопрос консоли прописывал yes.


![error](https://user-images.githubusercontent.com/26064824/30240494-d9326a44-95a3-11e7-92be-90de377a37c9.png)


![error2](https://user-images.githubusercontent.com/26064824/30240496-dc31299c-95a3-11e7-87fd-111bf3db939c.png)


![error3](https://user-images.githubusercontent.com/26064824/30240497-de625150-95a3-11e7-8919-18278f19c4cc.png)

**Comment by dhilt** [comment]
@BitDen Надо было вмержить db в бранч с дальнейшей разработкой. Назад дороги нет. Давай кстати поступим так. Возьми бранч dev, синхронизируй его с мастером (я недавно делал мерж из trans... в мастер, ты можешь видеть, что они synced), потом влей в dev бранч db и продолжай работу в бранче dev. А transl... мы удалим. При полной зачистке, удаляй не только node_modules, но и package.json.lock.

**Comment by BitDen** [comment]
@dhilt Хорошо, сделаю. Кстати насчет package-lock.json, может его стоит внести в gitignore?

**Comment by dhilt** [comment]
@BitDen Нет, его по идее комитить надо https://docs.npmjs.com/files/package-lock.json. То, что советую зачищать его, неправильно, но по моей практике ингода без этого никак. Я думаю, вскоре это нововведение устаканится и им можно будет пользоваться без проблем. Пока, если честно, не хочется пытаться в это кникнуть. Когда Node 8 перейдет в lts.

**Comment by BitDen** [comment]
@dhilt Бранч dev готов.

**Comment by dhilt** [comment]
@BitDen В этой задаче, посмотри README. Я подправил инструкцию в плане установки 5 elasticsearch (в мастере), нужно удостовериться, что там все актуально в плане снапшотов и подправить, если нет.

**Comment by BitDen** [comment]
@dhilt Так, 3-ий пункт по созданию снапшота, там написано: `This will create "/path_to_backups/my_backup/snap1" folder and fill it with elastic snapshot stuff.`. В моем случае выпадает несколько файликов прямо в папку "/path_to_backups/my_backup/"...

**Comment by BitDen** [comment]
@dhilt Ну и возможно стоит как-то обмолвиться в параграфе о восстановлении с помощью снапшота, что должен быть выполнен первый пункт по созданию снапшота, то есть `Register a snapshot repository`. Наверное вполне возможна такая ситуация, что некто в виде администратора, допустим, попытается восстановиться с помощью снапшота, при этом не проводив манипуляций по созданию снапшота ранее.

**Comment by dhilt** [comment]
@BitDen Окей! оставляем readme как есть
