### ISSUE TITLE
Search by Russian lang

### ISSUE THREAD

**Issue by dhilt** [dhilt/dharmadict#14]
Создаем тестовый термин ("test"), заполняем 1 перевод ("тест") и ожидаем, что поиск по "тест" выдаст нам термин "test". Сейчас это не так и надо разобраться с процедурой поиска.

**Comment by dhilt** [comment]
@BitDen Приоритет этой задачи ниже, чем у README и синхронных тестов с эластиком.

**Comment by BitDen** [comment]
@dhilt Я так понимаю, для этой задачи надо использовать решение вроде этого https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-lang-analyzer.html#russian-analyzer?

**Comment by BitDen** [comment]
@dhilt Не понимаю пока как бы с помощью эластика это сделать, но пока зародилась идея просто-напросто написать функцию, с помощью которую полученную строку преобразовывать из русской в английскую и полученный результат передавать в метод searchByPatter на server.js:
```
app.get('/api/search', (req, res) => {
  let pattern = translateFunc(req.query.pattern);
  termsController.searchByPattern(pattern)
    .then(result => res.json(result))
    .catch(error => sendApiError(res, 'Search error', error))
});
```

**Comment by BitDen** [comment]
@dhilt Хм, удалил в эластике индекс. Просто задал маппинг:
```
curl -XPUT 'localhost:9200/dharmadict?pretty' -H 'Content-Type: application/json' -d'
{
    "mappings" : {
        "terms" : {
            "properties" : {
                "wylie" : { "type" : "text", "analyzer": "russian" }
            }
        }
    }
}
'
```

И вроде как получилось:

![screenshot from 2017-09-12 07-26-15](https://user-images.githubusercontent.com/26064824/30301201-de4aade0-978b-11e7-80e5-9a07a9d36013.png)

Это ведь и есть желанный результат?

**Comment by dhilt** [comment]
@BitDen Это похоже на правду, я хочу еще немного поиграться с этим и потом надо будет обновить db-reset и стартовый снапшот.

**Comment by dhilt** [comment]
@BitDen Я засунул `"analyzer": "russian"` во все поля на маппинге в 20170908161900_create_index.js и не могу найти, например, по слову "явления". При этом поиск по слову "дхамма" работал и раньше, проверить это можно на dharmadict.ru, где маппинг изначальный. 

Так что нет.

**Comment by dhilt** [comment]
@BitDen Мне кажется, я сделал фикс https://github.com/dhilt/dharmadict/commit/aa52d7af354e5baf6dc981d3269c162167a4751d

**Comment by dhilt** [comment]
@BitDen Я слил dev в master и выложил на сервер

**Comment by BitDen** [comment]
@dhilt Попробовал на 10 разных словах и переводах, вроде как да, все ищется.

**Comment by dhilt** [comment]
@BitDen Спасибо! 
нет маппинга "analyzer": "russian" нет нигде сейчас
