### ISSUE TITLE
Translator list on UI

### ISSUE THREAD

**Issue by dhilt** [dhilt/dharmadict#15]
На клиенте есть файл translators.js. Нужно его ликвидировать. Вместо него данные должны приходить с сервера. У нас уже есть findAll. Нужен API метод GET /api/common, который будет отдавать весь список пользователей с ролью translator. Вызывать его нужно на старте приложения. В index, там где вызываются getUserInfoAsync и selectTermAsync. Нужно написать еще один action: getCommonDataAsync. Он будет стандартным для приложения способом обращаться к серверу через GET /api/common и получать список переводчиков. Это будет верхнеуровневый state common:

```
common: {
  translators: null
}
```

Внимание! сервер отдает не массив userInfo, а массив урезанных данных. На клиенте не должно быть логинов переводчиков.

**Comment by BitDen** [comment]
@dhilt Action и API готовы: https://github.com/dhilt/dharmadict/commit/b4a45dfd3d625792ed144e1dfa7ff7b4dba6459f
Также это дело провел в `components/search/Term.js` и удалил файл translators.js: https://github.com/dhilt/dharmadict/commit/3ec79d57d3ad18c90e0b3e76f80a566b05250ae5

**Comment by dhilt** [comment]
@BitDen Хорошо! Я не запускал, но выглядит все окей. Но переименуй GET_ALL_TRANSLATORS_START и GET_ALL_TRANSLATORS_END в GET_COMMON_DATA_START и _END соответственно. И давай сразу же расширим понятие common-data в этом проекте. См https://github.com/dhilt/dharmadict/issues/17

**Comment by BitDen** [comment]
@dhilt Переименовал и также перенес action getCommonDataAsync из `actions/translators.js` в `actions/common.js` - https://github.com/dhilt/dharmadict/commit/85b043484fd484880639dc110601b80216a9a612.
