### ISSUE TITLE
Languages API

### ISSUE THREAD

**Issue by dhilt** [dhilt/dharmadict#17]
Нужно добавить в API выдачу массива зыков. Для этого 

__1)__ добавь в helper.js

```
const languages = {
  data: [
    {
      id: 'rus',
      name: 'русский',
      name_rus: 'русский',
      name_eng: 'russian',
      default: true
    },
    {
      id: 'eng',
      name: 'english',
      name_rus: 'английский',
      name_eng: 'english'
    }
  ],
  getLang: function (id) {
    const lang = this.data.find(lang => lang.id === id);
    return lang ? lang.id : this.data.find(lang => lang.default).id
  }
}
```

__2)__ замени все вхождения строк 'rus' и 'eng' на вызов 

```
languages.getLang('rus'/'eng')
```

__3)__ добавь в `app.get('/api/common', ...`  массив зыков

```
{success: true, translators: ..., languages: languages.data }
```

После этого на клиенте положи этот массив в state `common.languages`. И замени все вхождения 'rus'/'eng' на languages[].id, а также строки "русский"/"английский" на languages[].name_rus

**Comment by BitDen** [comment]
@dhilt Вроде готово: https://github.com/dhilt/dharmadict/commit/23f01492d8546922adb6ed33ea4ff3620101bb15

**Comment by BitDen** [comment]
@dhilt Проблему с Edit.js пофиксил - https://github.com/dhilt/dharmadict/commit/00070be7d98d75e64c327c93239b78c37fcbbb57.
Просто на одном action'е неправильно брались данные с серверного ответа.

**Comment by dhilt** [comment]
@BitDen Хорошо! я снова не могу запуститься оркально, но я сделал небольшой рефакторинг и это требует проверки на работоспособность, и еще нужны тесты на новый API: https://github.com/dhilt/dharmadict/issues/18

**Comment by BitDen** [comment]
@dhilt Все просмотрел, единственное что пришлось сделать, это return дописать в getUserInfo.
И еще хочу предложить, чтобы параметр `isPublic` в getUserInfo всегда был по умолчанию true. Логин мы отдаем один лишь раз, когда создаем токен только что авторизорованному пользователю. В общем взгляните - https://github.com/dhilt/dharmadict/commit/3bce65bc41099144fe0da7fb78308845be4f323b

**Comment by dhilt** [comment]
@BitDen Обычно аргументы по умолчанию имеют значение false, чтобы не делалось лишних присваиваний, поскольку в ES5 такой код (`listen = (el = true) => el ? do(el) : null`) превращается в 

```
listen = function(el) {
  if (el == null) {
    el = true;
  }
 return el ? do(el) : null;
};
```

тогда как вариант с undefined по умолчанию (он же false в плане трактовки значения переменной-флага) транспилируется без изменений. 

И второе есть соображение: неизменность прежних вызовов. Если нет существенной разницы, то предпочтительнее добавлять функционал без изменения старого. То есть только на расширение.

Но пусть будет так.

**Comment by dhilt** [comment]
@BitDen babel 5 делает следующее.

```
listen = (el = true) => el ? do(el) : null
```
становится

```
listen = function () {
  var el = arguments.length <= 0 || arguments[0] === undefined ? true : arguments[0];
  return el ? do(el) : null;
};
```

Тогда как обратная логика

```
listen = (el) => !el ? do(el) : null
```

приводит к 

```
listen = function (el) {
  return !el ? do(el) : null;
};
```

**Comment by BitDen** [comment]
@dhilt Ну и дела. Подобное относится ко всем языкам программирования или же это такой случай из-за babel?
Можно и переписать обратно, но тогда придется в очень многих местах дописывать второй аргумент true. Почти все данные, что отдаем с сервера, почти все публичные.

**Comment by BitDen** [comment]
@dhilt А, можно поступить хитрее. Сделать переменную isNotPublic или что-то вроде этого. И избежим случая с лишними сравнениями, и лишь в исключительных случаях будем приписывать второй аргумент в getUserInfo.

**Comment by dhilt** [comment]
@BitDen Надо оставить это в покое. Тем более, что это nodejs, там никакой транспиляции нет 
😄😄😄
