### ISSUE TITLE
API common tests

### ISSUE THREAD

**Issue by dhilt** [dhilt/dharmadict#18]
Нужно написать тесты на /api/common. Просто проверить, что приходят данные по 2 тестовым пользователям и по 2 языкам.

**Comment by BitDen** [comment]
@dhilt Готово: https://github.com/dhilt/dharmadict/commit/5ac9981ada307eb8706b346b1e2e5e114a9f111f

**Comment by dhilt** [comment]
@BitDen Хорошо! перепиши немного тело теста

1) спрева проверь на приход обоих массивов

```
assert.equal(!!languages, true)
```

2) потом на непустоту

```
assert.equal(languages.length === 2, true)
assert.equal(translators.length >= 2, true)
```

3) а потом на вхождение, но с положительной логикой

```
assert.equal(!!translators.find(user => user.id === testTranslator.id), true)
```

**Comment by BitDen** [comment]
@dhilt Переписал - https://github.com/dhilt/dharmadict/commit/51afd31358785ccaf7c9712d3e723a49664e453e.

**Comment by dhilt** [comment]
👍
