### ISSUE TITLE
New term API: sanskrit

### ISSUE THREAD

**Issue by dhilt** [dhilt/dharmadict#20]
4 дополнительных поля должны появиться у нового термина. На примере термина "chos nyid" –

sanskrit_eng: "dharmata"
sanskrit_eng_lower: "dharmata"
sanskrit_rus: "дхармата"
sanskrit_rus_lower: "дхармата"

Для этого нужно добавить контролов на http://dharmadict.ru/newTerm, по одному инпуту на каждый язык из common.languages. В данном случае это будут sanskrit_eng и sanskrit_rus. Научиться сохранять их на сервере; _lower версии получаются через .toLowerCase(). 

Дописать тесты на создание термина!

**Comment by BitDen** [comment]
@dhilt Вроде готово - https://github.com/dhilt/dharmadict/commit/cd482386a564d07cb7eca08d9b751c31e2fbcd8f.
После создания термина, нам в ответ приходит лишь id термина, так что совсем чуточку там дописал.

**Comment by dhilt** [comment]
@BitDen Я провел рефакторинг кода, касающегося этой части. Осталось довести тесты, это я предлагаю сделать тебе:

 - нужны тесты на отсутствие объекта sanskrit и на неправильный тип данных внутри объекта sanskrit;
 - добавь проверку в валидатор, чтобы к-во полей в sanskrit соотв. кол-ву языков (иначе Invalid sanskrit) и напиши тест для случая отправки только одного, скажем sanskrit_eng;
 - обязательно нужно проверить lower case в результате успешного создания термина;
 - для этого допиши метод контроллера: найди термин по id и выдай его (как в update, но без перерводов).

Внутри then необязательно писать return Promise.resolve(some); достаточно просто return some; – then сам обернет это в resolved промис. Я переписал контроллер terms в соотв. с этим.

Если по моим комитам есть вопросы -- пиши!

**Comment by BitDen** [comment]
@dhilt С коммитами все вроде как понятно. Тесты дописал - https://github.com/dhilt/dharmadict/commit/9cde954620f028e5f3f7211510719ccb0567738a.
