### ISSUE TITLE
API contracts refactoring

### ISSUE THREAD

**Issue by dhilt** [dhilt/dharmadict#22]
Нужно привести в порядок адреса API методов. На примере User:

 - POST /api/users для создания пользователя
 - PUT /api/users/:id для редактирования пользователя по id 
 - GET /api/users/:id для получения пользователя по id
 - GET /api/users для получения списка пользователей

Как ты понимаешь, это потребует изменений как на сервере, так и на клиенте. Причем на update нужно перенести id из body запроса в url запроса. Пилить метод update контроллера не придется, т.к. он и так принимает 2 параметра отдельно.

То же надо проделать и для Terms. Все базовые обращения должны начинаться с /api/terms. Пока этому отвечает только DELETE. GET /api/search надо заменить на GET /api/terms, а GET /api/translation на GET /api/terms/translation. И т.п..

В общем, см. https://en.wikipedia.org/wiki/Representational_state_transfer в части "Relationship between URL and HTTP methods". Кстати, на update наверное следует использовать PATCH вместо PUT, т.к. мы не создаем новый документ в БД, если документ не был найден по id, мы возвращаем ошибку.

Все тесты должны проходить, их тоже придется править.

**Comment by BitDen** [comment]
@dhilt Вроде все готово. Эти дела расплылись на 6 коммитов, так что прикреплять их не буду. Из необычного было только то, что fetch отказался понимать метод PATCH, если его передавать строкой с строчными буквами.

**Comment by BitDen** [comment]
@dhilt Подумал, может стоит на вспомогательном методе asyncRequset в этом месте https://github.com/dhilt/dharmadict/commit/1c808f02a66a78bf010479aed4a5f4fcbc16de16#diff-59ef6f2c45355375ebb02fd8013a4297R13 получаемый тип запроса попросту приводить к заглавным буквам с помощью `.toUpperCase()`. Так можно будет в будущем наверное избежать некоторых недопониманий с fetch.

**Comment by dhilt** [comment]
@BitDen Мне нравится идя с toUpperCase, если есть с этим проблемы. Наконец-то у нас порядок с API

**Comment by BitDen** [comment]
@dhilt Добавил toUpperCase: https://github.com/dhilt/dharmadict/commit/973df8d01e6fed81b383b46ae33ab383252c02e5.
