### ISSUE TITLE
New translations CSV

### ISSUE THREAD

**Issue by dhilt** [dhilt/dharmadict#23]
У нас есть новый перевод, но он в неправильном формате. Нужно перегнать его в правильный формат, а именно трехколоночный CSV. Даже двухколоночный: __wylie__ и __transations__, поскольку нет комментариев. Данные должны идти по алфавиту wilye.

[Майя Малыгина.docx](https://github.com/dhilt/dharmadict/files/1329297/default.docx)

Добавь его в процесс db-reset и проверь, что он подцепился.

Новый пользователь выглядит так

```
{
  id: 'MM',
  body: {
    role: 'translator',
    login: 'mm',
    name: 'М. Малыгина',
    hash: '...', //сгенерируй сам от строки "mmpass", используя passwordHash
    language: 'rus',
    description: ''
  }
}
```

Меняй созданные скрипты, на смотря на дату в названии.

**Comment by BitDen** [comment]
@dhilt Готово и все вроде бы работает - https://github.com/dhilt/dharmadict/commit/e67d06a7a4ca64112c0eb2b229a1ef3e579e6230.

**Comment by BitDen** [comment]
@dhilt С переводами есть только две заминки:

1. В вашем прикрепленном документе есть похоже некая путаница между 113-м и 116-м термином. Не до конца понятно какой перевод кому принадлежит.
2. И не понятно что между 146-м и 147-м термином в файле. Я увидел просто термин без перевода и без нумерации и просто его одинокого такого вписал в csv-файл.

**Comment by BitDen** [comment]
Возможно, переводы терминов с 113-ого по 116-й должны выглядеть так?
```
rtog pa, Концептуальное сознание; мысленное обозначение; исследование
rtogs pa, познавать; постигать; постижение; познание; свершение
sbyin pa, даяние
sdig pa, моральный проступок (грех); скорпион
```

**Comment by dhilt** [comment]
@BitDen Прекрасная работа! Я провел сопоставление, на мой взгляд ошибок нет.

**Comment by BitDen** [comment]
@dhilt Значит термины "rtogs pa" и "thug pa med pa" были без переводов?

**Comment by dhilt** [comment]
@BitDen Да, я не увидел переводов, а окрестные совпали по смыслу с работами других переводчиков.
