### ISSUE TITLE
dispatch refactoring

### ISSUE THREAD

**Issue by dhilt** [dhilt/dharmadict#3]
Код испещрен конструкциями вида `dispatch={this.props.dispatch}` – это явно рудимент. Можно ли разобраться с этим, убрать лишнее?

**Comment by BitDen** [comment]
@dhilt Как я смог понять, другого способа иначе как писать `this.props.dispatch(myFunction())` не существует: https://stackoverflow.com/questions/33221634/why-use-this-props-dispatch-rather-than-store-dispatch-directly-in-redux

**Comment by BitDen** [comment]
Хотя, может быть возможно dispatch'и перенести в `./app/actions`. И на месте компонентов просто использовать импортируемые функции, допустим вместо `this.props.dispatch(doLoginAsync())` писать `doLoginAsync()`. Буду пробовать пока что такой вариант...

**Comment by dhilt** [comment]
@BitDen Да нет же, я имею в виду декларативную передачу метода dispatch через свойства компонента. Взять например компонент App. В нем вызывается компонент Nav, которому навязано свойство dispatch:

```
<Nav  ...
          dispatch={this.props.dispatch}
          ... />
```

Сам компонент Nav при этом коннектится к redux-store, что по идее само по себе обеспечивает ему наличие this.props.dispatch. То есть это свойство, должно быть, лишнее. И таких свойств миллион. Надо убедиться, что наличие connect позволяет избавиться от непосредственной перердачи метода dispatch и зачистить код.

**Comment by BitDen** [comment]
@dhilt Оу, а я вот-вот сейчас создал коммит с примером как бы могло выглядеть то, что я предлагал: https://github.com/dhilt/dharmadict/commit/1064cf5be62d8a2f27fa384b7e30f2f0835a1153.
Но это значит лишнее, да?

**Comment by BitDen** [comment]
Пока что все верну на свои места и буду убирать методы dispatch там, где они не нужны.

**Comment by BitDen** [comment]
@dhilt Прошелся по всем компонентам в общем и наделал несколько больше делов:

1. В двух компонентах Home и App совершенно ни к чему connect, убрал это дело. Помимо этого с компонента App в тег <nav /> передавались несуществующие параметры (кроме location - возможно удаляя его, я погорячился, но я правда не нашел в дочерних компонентах применения этой переменной и смысла в этой передаче). И удаление несуществующих параметров раскрыло проблемы, описанные в следующем пункте. 
Коммит по этому пункту: https://github.com/dhilt/dharmadict/commit/e4387681d930fdb7ae955533108690936e7befb0 (и сейчас заметил что забыл в PropTypes удалить ненужные переменные...)

2. На компоненте ./common/Nav.js переменная navButtons определяла свое содержимое, исходя из несуществующей переменной this.props.loggedIn и в итоге тернарное выражение всегда выдавало false. Плюс там еще была несуществующая переменная this.props.currentlySending. Из-за этих двух переменных (которые должны были прийти с App) не показывалась кнопка dashboard. И вообще честно говоря переменная navButtons выглядит довольно странно - дважды делается запрос аля `this.props.data.loggedIn ?`. Кажется над этим стоит подумать еще.
Коммит: https://github.com/dhilt/dharmadict/commit/25684eeee7dc448f84eceeb47432855d4742a83e.
Вдобавок в коммите удалил несуществующий state.route.prevLocation на Edit, поправил обращение к переменной term на NewTerm, убрал передачу dispatch'ей на Login и Logout, чуть-чуть докопался до верстки на SearchResults, убрал ненужный приведение типа SearchInput.

3. Исправив тернарное выражение на Nav, похоже впервые подключился компонент LoadingButton и приложение упало. Ибо как выяснилось, в компонентах ErrorMessage, LoadingButton, LoadingIndicator отсутствует подключение react-библиотеки.
Коммит: https://github.com/dhilt/dharmadict/commit/ce08038b71a1d350acee16337e89af2484af8b12

**Comment by BitDen** [comment]
@dhilt Сейчас вот думаю, может было бы выгоднее для производительности оставить декларативную передачу `dispatch={this.props.dispatch}` на компоненте Nav, а на компонентах Login и Logout убрать connect?

Еще заметил что нигде не используется компонент ./common/Form.js, возможно он раньше служил для авторизации и его стоит уже удалить?

И так ли важен PropTypes? Допустим есть ли в нем вообще смысл в подобном коде:
```
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import LoadingIndicator from './LoadingIndicator'

function LoadingButton (props) {
  return (
    <a href='#' className={props.className + ' btn btn--loading'} disabled='true'>
      <LoadingIndicator />
    </a>
  )
}

LoadingButton.propTypes = {
  className: PropTypes.string
}

export default LoadingButton
```

**Comment by BitDen** [comment]
@dhilt И да, насчет инфраструктуры внутри папки ./app/components я глубоко заблуждался, все там отлично. Один файлик - один роутер, дополнения к главному компоненту в отдельной папке. Но, может стоит Nav, Login, Logout из папки common перенести в еще не созданную папку app или auth? Все же эти компоненты сложно назвать общими.

**Comment by BitDen** [comment]
@dhilt И последний вопрос :)
Может стоит ./app/index.js разбить как в предыдущем проекте на index.js и routes.js?

**Comment by BitDen** [comment]
Переменную navButtons на компоненте Nav точно надо пересмотреть, у админа не показывается кнопка для создания нового слова:
```
let navButtons = this.props.data.loggedIn ? (
      <div>
        <Link to='/dashboard' className='btn btn--dash btn--nav'>Dashboard</Link>
        {userInfo.pending ? (
          <LoadingButton className='btn--nav' />
        ) : (
          <Logout />
        )}
      </div>
    ) : (
      <div>
        {this.props.data.loggedIn ? (
          <span>
            {userInfo.name}
            <Logout />
            {userInfo.role === 'admin' ? (<Link to={`/newTerm`}>New term</Link>) : ''}
          </span>
        ) : (
          <Login />
        )}
      </div>
    )
```

**Comment by BitDen** [comment]
Может быть вот так (все сработало отлично):
```
let newNavButtons = this.props.data.loggedIn ? (
      <div>
        <Link to='/dashboard' className='btn btn--dash btn--nav'>Dashboard</Link>
        <Logout />
        {(userInfo && userInfo.role === 'admin') ? (<Link to={`/newTerm`}>New term</Link>) : null}
      </div>
    ) : (
      <div>
        {this.props.data.userInfo.pending ?
          <LoadingButton className='btn--nav' /> : <Login />
        }
      </div>
    )
```

**Comment by dhilt** [comment]
@BitDen Разбирая dev-бранч, я вижу следующие моменты:

1. Исчез вывод имени залогиненного пользователя (см https://github.com/dhilt/dharmadict/blob/master/app/components/common/Nav.js#L30 ранее).

2. Исчезла ссылка на создание нового термина (см https://github.com/dhilt/dharmadict/blob/master/app/components/common/Nav.js#L32 ранее).

3. Кнопку Dashboard следует ликвидировать. То, что она оставалась в шаблоне, было неправильно. Ее нужно было убрать из шаблона, но не пытаться показать.

4. Компонент Form – кандидат на удаление.

5. Пусть Login коннектится к redux-store, там слишком много действий происходит. А Logout вполне можно сделать presentational; передать ему из Nav метод doLogout, который вызывает соотв. action (но не из компонента Logout, а из Nav).

6. Я не против создания папки auth в компонентах. Тогда можно было бы выделить еще компонент ./components/common/auth/Form.js, и открепить Login от redux-store, доставив ему методы doOpenModal, doCloseModal и doLoginAsync из компонента Nav. При этом методы onLoginChange  и onPasswordChange из Login уходят и появляются в Form, который берет их из actions в виде changeLoginString и changePasswordString и коннектится к redux-store.

7. На счет выделения routes могут быть проблемы из-за доп. методов checkAuth и unauthorizedAccess. Я бы не хотел сейчас тратить время на внедрение другого механизма аутентикации (отличного от onEnter, который ушел из react-router 4), но я не против того, чтобы просто попытаться разбить index на два файла.

8. И да, пропихивать store (ради dispatch) на actions плохая практика. Для этого есть первый аргумент thunk-версии action:

```
export function getUserInfoAsync() {
  return (dispatch, getState) => {
    ...
```

**Comment by BitDen** [comment]
@dhilt Про имя пользователя забыл совсем, каюсь, но 2-ой пункт решало создание новой переменной navButtons, которую я описал двумя своими последними комментариями, просто не внес. Вот коммит, кнопку Dashboard убрал: https://github.com/dhilt/dharmadict/commit/d9f049aa0d474d3191c968c2ef05c21d6b787ab0

Насчет 3,4,5 пунктов. Form пока оставляем на своем месте и не трогаем, да? И насчет создания presentational есть такой вопрос, поставлю его на примере Login. Почему бы нам не передать в него один лишь dispatch, а на самом компоненте не импортировать actions и там уже в локальных функциях дергать actions?

Касательно 7-ого пункта я просто имел ввиду одно лишь визуальное дробление на два файла, ради удобства, не из-за аутентификации. Но теперь хочется спросить, а есть ли смысл переходить на react-router 4?

И последний вопрос, оставим dispatch'и на компонентах как `this.props.dispatch()` или попытаемся dispatch спрятать в actions функциях?

**Comment by dhilt** [comment]
@BitDen 

Старый Form убираем в соотв. с п.4, новый Form порождаем в ./components/common/auth в соотв. с п.6.

Смысл presentational компонента в том, что он ничего не знает о redux (и actions); все redux-методы приходят в виде свойств компонента из разметки родительского компонента. Поэтому либо мы коннектим компонент к redux-store, импортируем actions и пользуемся dispatch, либо декларативно передаем все необходимые действия через свойства.

На 4 роутер не будем переходить, но я не против разделения index.

Ты не сможешь обойтись без dispatch в компонентах без прямого импорта store в actions. Thunk-dispatch эту задачу не решает. Action must be dispatched from a component. Но передавать dispatch через свойства, вопреки connect неправильно.

**Comment by BitDen** [comment]
@dhilt Form.js удалил, компонент Nav с Login и Logout перенес в ./components/common/header и сделал Login с Logout presentational-компонентами. Замысел создавать еще и Form вдобавок к Login не понял к сожалению, придется ведь Login коннектить к redux для changeLoginString и changePasswordString, а мы его наоборот же хотим избавить от знания о redux'е.
Коммит: https://github.com/dhilt/dharmadict/commit/ad885b247d767684bda64e1c0b0c4600052c3260

**Comment by BitDen** [comment]
@dhilt Результаты моих попыток разделить index.js: https://github.com/dhilt/dharmadict/commit/64dfa21c7b3da7d90218ac8b5154c1dae0cb22f1

**Comment by dhilt** [comment]
@BitDen Хорошо! я уезжаю на день в Финляндию, подумай пока над страницами переводчиков, создай issue и бранч

**Comment by BitDen** [comment]
@dhilt Подумаю конечно. Бранч стоит порождать вероятно от `dev`?

**Comment by dhilt** [comment]
@BitDen Все окей, я сделал мержи, бранч dev пусть существует, будем использовать его периодически (главное не забывать синкать его с мастером перед использованием).
