### ISSUE TITLE
Alerts/notifications

### ISSUE THREAD

**Issue by dhilt** [dhilt/dharmadict#30]
Нужна система попапов. Предлагаю новое верхнеуровневое состояние notifications вида

```
notifications = [
  {
    id: 1,
    type: 'info', // 'danger', 'success' etc
    text: 'Hello!',
    ttl: 2500, // 0 or undefined for eternal view
  }
]
```

и к нему компонент Notifier, врендеривающийся прямо на App Component 

```
      <Notifier />
      <div className='wrapper'>
        <Header />
        <div className='container'>
          {this.props.children}
        </div>
      </div>
```

Если кто-то хочет выдать нотификацию, пусть дергает action `notify`, принимающий параметры, соотв. одному элементу state.notifications. Через reducer происходит пополнение массива нотификаций.  Подумай, кто должен опутать новый элемент state.notifications логикой, а именно: создать таймер, дать возможность ручного закрытия. Возможно сам компонент?

**Comment by BitDen** [comment]
@dhilt Сделал новый бранч и pr - https://github.com/dhilt/dharmadict/pull/31.
Навесил новый action на компонент со сменой пароля.

**Comment by dhilt** [comment]
@BitDen Проблема в том, что ты пытался мутировать объект состояния еще на стадии action. Можно это сделать через клон на action, но я подумал, что потом еще будет клон на reducer, и перенес push в reducer через spread. Также я ввел понятие сквозного уникального id, не опирающегося на длину массива. Теперь CREATE_NOTIFICATION выглядит идеально.

Я хочу продолжить рефакторинг.

**Comment by dhilt** [comment]
@BitDen Логика с таймером отправилась в actions: https://github.com/dhilt/dharmadict/pull/31/commits/7f681e436564b1899d0ab0eab07d627fb67aa3f0

1) Сделай default параметры. Если не передан ttl, type, то они берутся из defaultNotification. Все это в происходит actions перед отправкой в reducer.

2) Сделай передачу i18n токена в качестве параметра вызова notify

```
text: "EditUserPassword.new_password_success"
```

Пусть компонент сам решит, что если это токен, то нужен `FormattedMessage`, а если нет, то просто выводим текстом.

3) См https://react-bootstrap.github.io/components.html#alerts-closeable, сделай нормальный закрывающий `X` через onDismiss.

**Comment by BitDen** [comment]
@dhilt Все добавил - https://github.com/dhilt/dharmadict/commit/ccbe2a0957327c5f86bdca8eb6c9997620502c64.

**Comment by dhilt** [comment]
@BitDen Отлично! Наконец сопроводи, пожалуйста, все вызовы asyncRequest нотификациями вида

```
notifyOnResponse(dispatch, 'EditUserPassword.new_password_success', error)
```

я добавил соответствующий метод и применил его в updateAdminUserPasswordAsync

**Comment by BitDen** [comment]
@dhilt Вроде готово - https://github.com/dhilt/dharmadict/commit/c83b4ff91236807952029820314dc7ffebe05a1f, https://github.com/dhilt/dharmadict/commit/91ef754a3c4e603a68247187003f197bd3dd4717.
Еще заметил что с выключенной бд клиент зависает с вечным запросом от action'а 'GET_COMMON_DATA_START', и консоль от лица сервера пишет:
```
[1] (node:6087) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): [object Object]
```

**Comment by dhilt** [comment]
@BitDen Я внес ряд изменений в систему нотификаций, посмотри пожалуйста. Параллельно улучшил checkAuth. По-моему это устранило зависание на клиенте при выключенной БД. Сервер у нас действительно никак не защищен от проблем с БД. Ты можешь подумать на этот счет в отдельном бранче. Еще посмотри, пожалуйста, что мы можем сделать для тестирования front end? Для этого можно создать отдельную задачу и начать там обсуждение...

**Comment by BitDen** [comment]
@dhilt В некоторых случаях может понадобиться еще переменная для вставки в текст в FormattedMessage - сейчас пока что требуется только в NewTerm при успешном создание термина, но все же добавил это дело - https://github.com/dhilt/dharmadict/commit/24a20c10fe77cace09fee5c3e6855e8125167b10.

**Comment by BitDen** [comment]
@dhilt Создал задачу для тестов - https://github.com/dhilt/dharmadict/issues/32.
