### ISSUE TITLE
New Translation

### ISSUE THREAD

**Issue by dhilt** [dhilt/dharmadict#35]
Посмотри, пожалуйста, новый перевод

https://docs.google.com/spreadsheets/d/1WqNptg7tV11z32B4Q89DAFbFV7nDa-LZutJ-gY40zsM/edit#gid=193456624

На этот раз они постарались упростить нам задачу, но все равно нужно быть бдительным при импорте.

Так же нужно добавить переводчика: Ю. Жиронкина.

**Comment by BitDen** [comment]
@dhilt Я бы посмотрел, но при переходе по ссылке google-диск заявляет что нет доступа. Может файлик или что там сюда скинете?

**Comment by dhilt** [comment]
@BitDen Перезалил с нормальными правами: https://drive.google.com/file/d/0B3nPLUZLdfBOcVpqLTBVbG5FcUtjODFWbHdNQVNlMU1zWlZ3

**Comment by BitDen** [comment]
@dhilt Здорово, вижу.

**Comment by BitDen** [comment]
@dhilt Все добавил - https://github.com/dhilt/dharmadict/commit/5f7dbbb17bf40762dfc2cf8959ca9638376ba5ce. И вдобавок добавил ссылки на новых переводчиков на компонент About - https://github.com/dhilt/dharmadict/commit/5758edea8faa47d9afb0b8646c19a65694ed407a.

Только запутался немного с CSV. Как на клиенте должен выглядеть перевод термина chos "Дхарма; Учение, Святая Дхарма"? Именно такая вот строка и должна показываться клиенту или это должно показываться следующим образом:
```
1) Дхарма
2) Учение, Святая Дхарма
```

**Comment by BitDen** [comment]
А хотя да, вспомнил, перенос должен быть связан с "+", либо если бы в файлах переводы были бы написаны через 1), 2).

**Comment by dhilt** [comment]
@BitDen Въедливое замечание... мне тоже кажется странным, что "созерцание-медитация" идут как одно значение, а "медитация-сосредоточение" как 2. Но в документе так и мы оставим это так. Они сами отредакитуют, если передумают. Я сеегодня-завтра буду деплоить этот перевод и посмотрю еще раз в целом на результат.
