### ISSUE TITLE
Translator can change his password

### ISSUE THREAD

**Issue by dhilt** [dhilt/dharmadict#36]
Последнее, что нужно будет сделать для этого релиза: дать переводчикам возможность менять свой пароль. 

Нужен отдельный роут, не `/translator/:id/edit/password`, а скажем `/translator/:id/password` – на входе должна проверяться роль 'translator'.

Помимо "Нового пароля" и "Подтверждения" должно быть еще одно поле: "Старый пароль". То есть Переводчик не может сбросить пароль без ввода старого.

Кнопка "Сбросить" сбрасывает все три поля в пустую строку.

На сервере появляется новый обработчик.

**Comment by BitDen** [comment]
@dhilt Вроде все готово - https://github.com/dhilt/dharmadict/commit/6f76be9a9527e669371f6b393975b793fa6d4f47.

**Comment by BitDen** [comment]
@dhilt И отходя от темы этой задачи, думаю стоит немного поменять подход к показу ошибки. Сейчас мы текст, приходящий с сервера, выдаем за id, который по мнению i18n-библиотеки должен лежать в ru/en.json - в итоге при серверных ошибках в консоли вытекает много ошибок по i18n.

**Comment by BitDen** [comment]
@dhilt К примеру это могло бы выглядеть следующим образом - https://github.com/dhilt/dharmadict/commit/79537442b9a9d3e04a525d1dc30dbec9720f601d.

**Comment by BitDen** [comment]
@dhilt И вдогонку добавил тесты для серверной части этой задачи - https://github.com/dhilt/dharmadict/commit/663dd4b010d7490046a93e34a2a1d8321ad08539.

Может стоит перенести все тесты для backend в папку `test/backend`?

**Comment by BitDen** [comment]
@dhilt Взял на себя наглость и уже перенес - https://github.com/dhilt/dharmadict/commit/fe5c52cbf6791f834e2435cd5740862f5547a5d3.

**Comment by dhilt** [comment]
@BitDen Очень хорошие тесты и с /test/backend я согласен. только надо либо moch.opts загнать в /test/backend, либо jest.config.json положить в /test.

**Comment by BitDen** [comment]
@dhilt Чуть позже постараюсь переложить mocha.opts в /test/backend, с первого попытки что-то не вышло пока что.
