### ISSUE TITLE
Translator page

### ISSUE THREAD

**Issue by BitDen** [dhilt/dharmadict#4]
Нужно создать роут `/:name`, показывающий страницу с информацией об отдельно взятом переводчике.

**Comment by BitDen** [comment]
@dhilt В общем породил новый бранч от 'dev' и там произвел попытку сделать страницу с информацией о пользователе. Коммит: https://github.com/dhilt/dharmadict/commit/afad80bcd7c5a4cf6962febc4cd7fc6273374627

Сервер теперь распознает запрос '/api/user/:name', где name - это логин пользователя. И отдает данные о нем, которые судя по всему лежат в ./prod/user.js.
Появился новый роут '/user'. Ожидается использование в стиле `user?name=mk`. И также появился новый компонент TranslatorPage, который на моменте своего создания кидает новый action getTranslatorInfoAsync с сопутствующими dispatch'ами внутри.

**Comment by BitDen** [comment]
@dhilt Этот свежеиспеченный роут должен быть защищен от неавторизированных пользователей? И где собственно должны располагаться ссылки на роут?

**Comment by BitDen** [comment]
Добавил ссылку на Nav пока что: https://github.com/dhilt/dharmadict/commit/d8f2752075edd0bd47fe427381497fe72b9c739b

**Comment by dhilt** [comment]
@BitDen Во-первых, см issue https://github.com/dhilt/dharmadict/issues/5.

Роут соответственно не защищаем.

Можем ли мы сделать, чтобы роут выглядел не как /user?name=xxx, а как /translators/:login, где "login" берется из users.js? (don, hop и т.п.)

**Comment by BitDen** [comment]
@dhilt Много пытался, поглядывая на разные гайды вроде этого https://github.com/ReactTraining/react-router/blob/v3/examples/active-links/app.js, но что-то совсем ничего не идет пока...

**Comment by BitDen** [comment]
@dhilt Подправил запрос на сервере, чтобы отдавал только информацию о пользователе с ролью переводчика: https://github.com/dhilt/dharmadict/commit/e53e984262d7857019b2f762d0dc1e5153fe849a

**Comment by dhilt** [comment]
@BitDen Пока все хорошо. Следующие задачи на этом направлении:

 - перевести пользователей из JSON в Elastic (https://github.com/dhilt/dharmadict/issues/6);
 - дать суперадмину возможность редактировать описание переводчиков (https://github.com/dhilt/dharmadict/issues/7).

В последствии будем расширять возможности суперадмина, он будет уметь сбрасывать/устанавливать пароли для переводчиков, возможно создавать новых переводчиков... Но пока делаем все для создания страниц переводчиков.

**Comment by BitDen** [comment]
@dhilt Эта задача пусть пока в PROGRESS повисит наверное, чуть позже обязательно попытаюсь добиться роута вида `/user/:name`.

**Comment by dhilt** [comment]
@BitDen Давай пока закроем все же эту задачу. Сейчас роут выглядит как /translator?don и это уже хорошо.
