### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by dhilt** [dhilt/dharmadict#40]
Нужен новый тип документов в БД, Pages. Каждый Page имеет три редактируемых поля

 - url
 - title
 - text

Причем text произвольный, с html-разметкой.

**Comment by dhilt** [comment]
@khajjit Мастер обновлен! Взгляни бегло на мои правки (из основного: я пересмотрел значение user.description и добавил vendor bundle) и можно делать мерж в test-бранч. Постарайся привести тесты в соответствии с требованиями минимальной полезности и открывай PR на мастер.

Внешний сайт сейчас недоступен, но локально я, думаю, отладил достаточно. Буду разбираться, возможно проблемы с хостингом.

**Comment by khajjit** [comment]
@dhilt С правками все понятно, и изменения смержил уже - вроде все отлично (надо только тесты для фронтенда подправить чуток).

Не совсем понял, что же означают слова "привести тесты в соответствии с требованиями минимальной полезности"? Убрать лишние тесты, или же может написать только необходимые ключевые тесты (как мне видится это тесты для backend'а, и возможно на actions. Писать тесты на компоненты, как мне кажется, в действительности пустая трата времени, ибо логика внутри компонентов до невозможности простая)?
