### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by dhilt** [dhilt/dharmadict#5]
Добавить страницу о проекте так, как это было в первой версии приложения.

**Comment by dhilt** [comment]
@BitDen Я добавил страницу "О проекте". Просмотри ее, там перечислены переводчики. 

1) Актуализируй список переводчиков.
2) Сделай их ссылками на страницы переводчиков (через Link).

**Comment by BitDen** [comment]
@dhilt Добавил: https://github.com/dhilt/dharmadict/commit/502c7ddab57e1b5f5f62c2119d2c2cc056fba074
Пока с роутами не разобрался и переход выглядит так: `<Link to='/user?name=don'>`.

**Comment by dhilt** [comment]
@BitDen А есть шансы на роуты /translators/:code?
