### ISSUE TITLE
Translators DB

### ISSUE THREAD

**Issue by dhilt** [dhilt/dharmadict#6]
Необходимо избавиться от ./prod/users.js и перегнать всю информацию в ElasticSearch.

Возьми нетронутый дамп эластика (от момента первой версии проекта) – это будет нашей отправной точкой. Нужно его модифицировать, накатить на него данные по переводчикам. Эти данные должны храниться в том же индексе, что и переводы, т.е. в dharmadict. Посмотри https://www.elastic.co/blog/index-vs-type, это делается через типы. Сейчас есть тип 'terms', нужен новый тип 'users'.

Каждый документ нового типа имеет id, который должен соответствовать id из users.js, и body соответствующий остаточной структуре + новое поле description

```
{
    role: 'admin',
    roleId: 1,
    code: 'ADMIN',
    login: 'admin',
    name: 'Администратор',
    hash: '2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824',
    description: 'Some text...'
  }
```

Можешь для удобства добавить API для добавления/удаления пользователя. Мы не будем пока делать для этого UI, но будет полезно иметь соотв. методы на сервере. Дергать их можно будет через POSTMAN или любым другим методом.

После добавления пользователей в индекс, нужно отрефакторить приложение, чтобы оно опиралось на новые данные из elastic.

**Comment by dhilt** [comment]
@BitDen Давай поступим так. Создай ./prod/controllers/users.js и размести на нем несколько публичных (экспортируемых) методов:

 - findById(id), для работы authorize
 - findByLogin(login), для /api/login и для /api/translators/:name
 - findAll, понадобится для front end вместо ./app/helpers/translators.js

Эти методы ходят за данными в Elastic (см, например, реализацию функции getTermById), но пусть они возвращают данные в виде промисов. Пора начинать promise-рефакторинг.

**Comment by BitDen** [comment]
@dhilt Пока что застрял на моменте создания нового типа в уже существующем индексе 'dharmadict'. Опираясь на документацию https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html, пытаюсь следующим кодом создать новый тип:
```
  curl -XPUT 'localhost:9200/dharmadict/_mapping/users?pretty' -H 'Content-Type: application/json' -d'
  {
    "properties": {
      "role": { "type": "text" },
      "roleId": { "type": "integer" },
      "code": { "type": "text" },
      "login": { "type": "text" },
      "name": { "type": "text" },
      "hash": { "type": "text" },
      "description": { "type": "text" }
    }
  }
  '
```

Но сыпятся ошибки в ответ вида:
```
{
  "error" : "MapperParsingException[No handler for type [text] declared on field [role]]",
  "status" : 400
}

```

**Comment by dhilt** [comment]
@BitDen Я смотрю на Gruntfile из 1 версии проекта. Там есть отдельная команда для создания индекса (в задаче 'upload'), но нет отдельной команды для создания типа. Есть впечатление, что можно просто пихать в эластик документы с новым типом через elasticClient и новый тип создастся автоматически.

**Comment by BitDen** [comment]
@dhilt Хотим мы создать новый тип или изменить properties в уже существующем типе - код будет выглядеть одинаково, как я написал допустим.

**Comment by dhilt** [comment]
@BitDen Я все же считаю, что пытаться общаться с elastic не через elasticClient в данном случае лишний труд. Попробуй просто добавить средствами elasticClient новый документ в существующий индекс, указав ему новый тип. Так как это сделано для POST /api/newTerm. Никаких properties, ничего лишнего, в запрос уходят только index, type, id документа и body.

**Comment by BitDen** [comment]
@dhilt Написал это дело через elasticClient:
```
app.post('/api/newUser', function(req, res) {
  let newUser = req.body;
  newUser.hash = passwordHash.generate(newUser.password);
  delete newUser.password;
  let userId = newUser.login;

  elasticClient.indices.putMapping({
    index: 'dharmadict',
    type: 'users',
    id: userId,
    body: newUser
  }, (error, response, status) => {
    if (error) {
      logger.error('Create user error');
      return responseError(res, error.message, 500);
    }
    logger.info('User was successfully created');
    return res.json({
      success: true
    });
  });
});
```
Теперь сыпятся ошибки вида:
```
{
    "error": true,
    "message": "MapperParsingException[Root type mapping not empty after parsing! Remaining fields:   [role : translator] [roleId : 2] [code : HOK] [login : hok] [name : Hoking] [description : Some text...] [hash : sha1$77883eb5$1$f46e89213fd129093aa0e16054017a48951fb1e3]]"
}
```

**Comment by BitDen** [comment]
В req.body прилетает следующий объект:
```
{
    "role": "trasdanslator",
    "roleId": 2,
    "code": "HasdOK",
    "login": "hasdok",
    "name": "Hoasdking",
    "password": "hkpaasdss",
    "description": "Some text..as."
}
```

**Comment by BitDen** [comment]
@dhilt И за все время попыток нового типа 'Users' не появилось пока. Мне кажется надо это дело все-таки с properties проворачивать, все же логично наверно изначально задать какую-то структуру для так называемого типа, а затем его пичкать данными.

**Comment by BitDen** [comment]
@dhilt А с такой версия кода, где используется `ElasticClient.index({...` вместо `ElasticClient.indices.putMapping({...` все вроде получается, по крайней мере тип 'Users' точно создался в индексе 'dharmadict'.
```
app.post('/api/newUser', function(req, res) {
  let newUser = req.body;
  newUser.hash = passwordHash.generate(newUser.password);
  delete newUser.password;
  let userId = newUser.login;

  elasticClient.index({
    index: 'dharmadict',
    type: 'users',
    id: userId,
    body: newUser
  }, (error, response, status) => {
    if (error) {
      logger.error('Create user error');
      return responseError(res, error.message, 500);
    }
    logger.info('User was successfully created');
    return res.json({
      success: true
    });
  });
});
```

**Comment by dhilt** [comment]
@BitDen Да, в точности как на POST /api/newTerm. Из старой процедуры импорта через Grunt вполне очевидно, что с elasticClient отдельных телодвижений для создания нового типа не требуется.

**Comment by BitDen** [comment]
@dhilt Спустя долгое время первые результаты: https://github.com/dhilt/dharmadict/commit/45d761ff9f12d707281a012b283ef0107f7e07d9.
Теперь есть запрос для добавления пользователя в базу данных + запрос для поиска пользователя по его логину.
У меня собственно вопрос насчет id. Нам обязательно нужно делать поиск пользователя по числовому id, как в users.js. Если пользователь обязательно должен иметь поле id и цифровое значение - то как его собственно назначить? Это забота того, кто будет отправлять запрос на `/api/newUser` или это как-то автоматически надо находить?

**Comment by dhilt** [comment]
@BitDen Давай придерживаться существующей структуры, в которой есть id и код. При этом id по идее должен задаваться автоматически. Только код должен быть кристаллизирован. Id может быть произвольным, он роли не играет, но он должен быть уникальным.

**Comment by BitDen** [comment]
@dhilt И это будет нормально иметь id вида "AV5DG-D7Y9tyiqeoESgG"?

**Comment by BitDen** [comment]
Выходит на запрос вида `app.post('/api/findById'...` нужно будет присылать такие строки.

**Comment by BitDen** [comment]
Функция findById будет выглядеть следующим образом: https://github.com/dhilt/dharmadict/commit/816c8bf541e2b68abbd34e55491196fcd009c9d7.
А в качестве параметра будет брать `{ "id": "AV5DG-D7Y9tyiqeoESgG" }`.
Если это нормально, то буду приступать к рефакторингу. Если нет, придумаю что-то с обычными числами.

**Comment by BitDen** [comment]
Ну и стоит наверное учесть что такой id будет за пределами самого объекта, который распологается в `_source`.
```
{
      "_index" : "dharmadict",
      "_type" : "users",
      "_id" : "AV5DG-D7Y9tyiqeoESgG",
      "_score" : 1.0,
      "_source":{"role":"translator","roleId":2,"code":"MK","login":"mk","name":"MKMKMK","description":"Some text...","hash":"sha1$8b30d739$1$ebb3042c885c7c2e26522d4cba55dd04760e4816"}
}
```

**Comment by dhilt** [comment]
@BitDen Я еще раз подумал и давай все же вот как поступим. Мы упраздним понятие кода. Пусть код выступает в качестве id. Уникальность пусть будет на совести вызывающего API. То есть id = "DON" и т.п.. Если id будет передан неуникальный, эластик не даст создать запись, выкинет с ошибкой и это будет хорошо.

Итого имеем структуру пользователя 

```
{
    id: 'MK',
    role: 'translator',
    roleId: getRoleId('translator'),
    login: 'mk',
    name: 'М.Н. Кожевникова',
    hash: '34ury4goury3gfo3uyfg87f...',
    language: "rus"
  }
```

И клиент тоже нужно будет адаптировать под то, что у нас теперь код – это значение id.

**Comment by BitDen** [comment]
@dhilt Хорошо. Тогда теперь буду колдовать над ./prod/controllers/users.js и попутно просмотрю клиент по поводу id и code.

**Comment by BitDen** [comment]
@dhilt Вот первые результаты: https://github.com/dhilt/dharmadict/commit/9c725d55de8ee00038c8e701544ea38bd44bacc5.
Клиент пока не смотрел насчет id, но проблемы там возникли с доступностью функции править переводчику собственный перевод.
findByLogin() пришлось еще внедрять в запрос `/api/translation`, там вышел весьма запутанный (и похоже сейчас нерабочий) код, стоит над этим потом подумать. Да и собственно создать termControllers наверное...
Из проблем пока заметил, что метод create работает не так как ожидалось - при попытке создать пользователя с уже существующим id, он перезатирает существующего пользователя и создает нового. На этот случай похоже придется добавочно писать проверку на существование пользователя с якобы новым id.
Ну и рефакторинг, как я догадываюсь, вовсе не такой как ожидалось. Надо ведь будет на usersControllers убрать колбэки, и обратить их в then?

**Comment by BitDen** [comment]
@dhilt Может еще стоит создать ./prod/controllers/helpers/db.js - там у ElasticClient отбирать колбэки и менять их на promise, также туда закинуть responseError, redirect, getTokenFromRequest, возможно authorize. И это все экспортировать, куда понадобится.

**Comment by dhilt** [comment]
@BitDen Прекрасная работа! Я сделал небольшое ревью вокруг логина и создания пользователя. Никогда не передавай текст ошибки БД на клиент, только в серверный лог. 

Переведи авторизацию по токену на login вместо id https://github.com/dhilt/dharmadict/blob/cb44c0942d18300cd6a05fb18f60a2495aa4e5e2/prod/server.js#L65 и удали метод findById.

Мне нравится идея пропатчить elasticClient, но остальные дела (responseError, redirect, getTokenFromRequest) должны жить в отдельном хелпере. Метод авторизации должен будет перейти в controllers/auth.js. И туда же нужно будет аккуратно отрядить содержимоее /api/login – это будет метод doLogin, который будет вызывать метод на user-контроллере (который сейчас тоже называется doLogin, но который нужно будет переименовать в, скажем, canLogin).

Когда разгребем логин и авторизацию, будем чинить остальной API.

PS Убери, пожалуйста,  hash из getUserInfo в следующий заход, я забыл это сделать.

**Comment by BitDen** [comment]
@dhilt Удалил метод findById и hash из getUserInfo: https://github.com/dhilt/dharmadict/commit/be36afb6bf8554b2a06c9892620be7f349362dfb.
Сменил callback'и на promise на ElasticClient и подкорректировал работу методов на usersController: https://github.com/dhilt/dharmadict/commit/d003767c1a38eb43371d1c4ec8d27f8a464f4a75

**Comment by BitDen** [comment]
Далее создам controllers/auth.js. И вторым делом надо додумать создание нового пользователя на методе create, чтобы не перезатирал уже существующего с тем же id.
И что насчет Cookies? Убирать это дело или нет, не используется ведь нигде.

**Comment by BitDen** [comment]
@dhilt Наверное такая защита от перезатирания не пойдет https://github.com/dhilt/dharmadict/commit/9221f675074649d06614a24ac523413d993fc5d5? Скорее стоит создать метод на проверку уникальности у login и id вместе взятых. С тем что я написал, допустима ситуация где админ сможет новому пользователю задать уникальный логин, но если id уже существовал - то пользователь перезатрется.

**Comment by dhilt** [comment]
@BitDen Да, добавь туда еще один then с поиском пользователя по коду (id). Но давай не будем возвращать метод findById, а напишем новый метод findBy(key, value) и вызовем его на findByLogin (с аргументами "login" и userLogin) и на createUser (с "id" и newUser.id).

Cookies не нужен!

**Comment by BitDen** [comment]
Метод сделал: https://github.com/dhilt/dharmadict/commit/7ac8c11f0eb4b3ee5b3446ab5b2237867b907d2b.
Хотя возможно лучше было бы вернуть findById.

**Comment by BitDen** [comment]
@dhilt findBy сделать и для login, и для id одновременно не получится, код поиска в elasticSearch отличается.

**Comment by dhilt** [comment]
@BitDen Ах да, они же на разном уровне! id и login... оставь так, как ты уже написал. Хотя может быть действительно лучше было вернуть findById...

**Comment by BitDen** [comment]
Нет, не выйдет. В базе данных id все же стоит уровнем выше. Можно было бы такой метод написать для role, roleId, description и прочей информации о пользователе, но к id нужен другой запрос.

**Comment by BitDen** [comment]
@dhilt Да, пожалуй стоит вернуть findById, это будет логично. В общем-то в новом методе _checkUniqueOfLoginAndId я заново код от findById переписал, а он может еще и в других местах пригодиться.

**Comment by BitDen** [comment]
@dhilt В общем вернул метод findById, убрал _checkUniqueOfLoginAndId, думаю так будет лучше: https://github.com/dhilt/dharmadict/commit/96e6925bcc81922cc1d4e061696333117e3afc6b

**Comment by BitDen** [comment]
И вдогонку добавил проверку на то, какая именно ошибка пришла с методов findByLogin и _findById (может ведь быть не только отсутствие данных). И добавил комментарии, обговаривающие это, ибо это выглядит весьма неоднозначно. Коммит: https://github.com/dhilt/dharmadict/commit/dbbe37e7a23875bdb9b225bed8699863b4260474

**Comment by BitDen** [comment]
Далее займусь `./prod/controllers/auth.js`...

**Comment by BitDen** [comment]
@dhilt Вот первые результаты: https://github.com/dhilt/dharmadict/commit/80e0b0b9e39162124b9d0766ef507e45f73a22ee.
Создал auth.js с методами doLogin и authorize, и serverHelper.js (с тремя вспомогательными методами). Пожалуй осталась еще там пара не очень красивых мест, которые стоит преобразить - чуть позже доведу это до конца.

Ну и в общем на ./prod/server.js теперь не хватает только termControllers, чтобы все было здорово. И еще проблемы с code и id остается на клиенте, про это тоже не забываю.

И появилось предложение следующего рода - может быть стоит создать метод `responseSuccess`, эдакий родственник уже существующего `responseError`? Можно будет довести код до следующего вида:
```
app.post('/api/login', function (req, res) {
  authController.doLogin(req)
    .then(result => responseSuccess(user))
    .catch(error => responseError(res))
});
```
Насколько я припоминаю на клиенте есть метод AsyncRequest, который посылает fetch-запросы на сервер, и определяет их успешность по наличию у возвращенного объекта данных свойства 'status' или 'ok'. Наверное это может быть полезно.

**Comment by BitDen** [comment]
@dhilt И важный вопрос насчет авторизации. Hash, который лежит в объекте данных пользователя, его мы можем запихивать только в токен, и ни в коем случае не отдавать на клиент, так ведь?

**Comment by dhilt** [comment]
@BitDen Да, все, что ты говоришь, имеет смысл. Я сейчас хочу посмотреть на результат, порефакторить. Я планирую часа полтора посвятить этому. Так что ты пока не трогай сервер, (посмотри клиент, например).

**Comment by dhilt** [comment]
@BitDen Я закончил с авторизацией.

1) На сервере ставим ; в том случае, если это не последний оператор. Я отрефакторил весь по-моему код на эту тему. 

2) Auth controller переосмыслен, теперь он занимается только токеном.

3) Будем стараться не вызывать методы одного контроллера изнутри другого.

4) В новой promise-версии doAuthorize (server.js) не все чисто с бросанием и ловлей ошибок. Возможно, мы изменим это впоследствии, но пока имеется следующее ограничение: если в том месте, где будет использоваться doAuthorize, не будет общего catch, нужно писать catch-заглушку. Так как это сейчас сделано для GET /api/userInfo

```
  doAuthorize(req, res)
    .then(user => res.send(getUserInfo(user)))
    .catch(err => null);
```

Это связано с тем, что nodejs, не смотря на вызов res.send() внутри promise chain, будет пытаться завершить цепь обещаний. Поэтому в doAuthorize возникли лишние throw null и это надо перехватывать.

5) Знание о пароле в любом виде (будь то хэш или непосредственно строка пароля) клиенту не нужно.

**Comment by dhilt** [comment]
@BitDen Я решил отказаться от 302 редиректа средствами сервера. Теперь doAuthorize возвращает обычную ошибку, а клиент сам должен решать, что с этим делать. Возможно в будущем мы расширим, да, мы определенно расширим бросание строковых ошибок до собственного объекта, который будет включать в себя не только строку, но и код. 

Пока же я ввел конфигурационный объект на сервер, сделал /translator?[name] роут и заменил API метод по созданию пользователя с POST на PUT, т.к. мы с помощью текущего API не можем изменять сущность.

**Comment by dhilt** [comment]
@BitDen Я создал задачу для рефакторинга контроллеров https://github.com/dhilt/dharmadict/issues/8. Постараемся разделить обсуждения.

**Comment by BitDen** [comment]
@dhilt Хорошо. С кодом разобрался, все понятно, продолжу работать над termControllers уже.
Эту задачу уже можно считать закрытой или у нас остаются здесь еще какие-то цели?

**Comment by BitDen** [comment]
@dhilt Думаю еще может стоит убрать role или roleId на объекте данных у пользователя:
```
var Users = [{
    id: 1,
    role: 'admin',
    roleId: getRoleId('admin'),
    code: 'ADMIN',
    login: 'admin',
    name: 'Администратор',
    hash: passwordHash.generate('pass')
  }...
```
По сути ведь это дублированные данные.

**Comment by dhilt** [comment]
@BitDen Да, давай уберем roleId, это избыточные данные. Мне кажется, да, мы смешали много задач под одним соусом. Надо стараться разделять задачи, конечно.
