### ISSUE TITLE
Translator description edit

### ISSUE THREAD

**Issue by dhilt** [dhilt/dharmadict#7]
Суперадмин должен уметь редактировать текст описания переводчиков.

**Comment by dhilt** [comment]
Пока можно ограничиться написанием серверной части: метод на контроллере, API и тесты. Тестируем причем API, а не контроллер (как это было с create/delete users), поскольку этот функционал точно будет доступен через API в следующем релизе.

**Comment by BitDen** [comment]
@dhilt Вроде как готово: https://github.com/dhilt/dharmadict/commit/58dbe06cb69c6afe4e55aaa649465aebeeee4b29

**Comment by BitDen** [comment]
@dhilt Можно попробовать и визуальный компонент сделать, я правда слабо представляю как это будет выглядеть, но все же что-то да сделал бы.

**Comment by dhilt** [comment]
@BitDen Очень хорошо! Объедини, пожалуйста, проверки "No id" и "Invalid id" под одну крышу "Invalid id" (и то же самое с description). Тесты разные оставь, просто теперь текст будет один "Invalid..." Название переменной userDescription надо заменить на просто data. 

Далее, убери в контроллере `.then(() => findById(userDescription.id))` – дело в том, что doAuthorize (посредством findByLogin) возвращает полный объект пользователя. Просто добавь второй параметр к методу updateDescription, передай в него пользователя. 

После можешь попробовать UI.

**Comment by BitDen** [comment]
@dhilt Первое дело подправил, со вторым заминка. У нас ведь по затее только админ может пользоваться этим api, следовательно, с doAuthorize у нас спускается только объект данных админа. Ну, можно конечно на ./server.js добавить один `.then`. Но выйдет так, что мы просто один .then перенесем с usersController на server.js...

**Comment by BitDen** [comment]
@dhilt Роут брать вида `/admin/updateUser`?

**Comment by BitDen** [comment]
И еще забыл добавить проверку на попытку изменить описание, не будучи админом: https://github.com/dhilt/dharmadict/commit/cb9cb7175b6f410dc84eeba55ce0bb520de707cb

**Comment by BitDen** [comment]
@dhilt Наконец-то разобрался с проблемой у роутов. Заметил что больше одного `/` после `localhost:5000` браузер отказывается наотрез понимать, хотя вроде как даже на адрес вида `/a/b/c/d` должен выдывать NotFound. Потом полез в сторону express.js пытаться что-то сделать со статикой, там тоже ничего не помогало. И повезло наткнуться на следующий совет https://stackoverflow.com/questions/35929820/minimum-nodejs-server-setup-needed-for-react-using-react-router-and-browserhisto. Всего-навсего не хватало указания пути в главном html - `<base href="/">`. Кстати говоря, в проекте react-try такой проблемы не было, несмотря на отсутствие этой строчки в html...
Теперь можно будет спокойно сделать роут со страницей переводчиков как `/translators/mk`.

**Comment by BitDen** [comment]
И такая ошибочка с роутами проскользнула на dharmadict.ru собственно.

**Comment by dhilt** [comment]
@BitDen Ок, я пока посмотрю сервер и тесты.

**Comment by BitDen** [comment]
@dhilt В updateUserSpec забыл добавить один тест, попытку добавить описание к несуществующему пользователю, сейчас дописываю.

**Comment by BitDen** [comment]
@dhilt Вперемешку с вашим коммитом, но все же дописал: https://github.com/dhilt/dharmadict/commit/08d8db1ff2be286f696dd80276ac42d71e263ef2

**Comment by dhilt** [comment]
@BitDen Хорошо, пока не трогай сервер больше, я хочу еще api немного пересмотреть.

**Comment by BitDen** [comment]
@dhilt Окей, буду дальше додумывать UI для админа на клиенте.

**Comment by dhilt** [comment]
@BitDen Я обновил api. Теперь есть api общего назначения POST /api/updateUser. Контракт следующий

```
{
  userId: 'user-id',
  payload: {
    description: "text..."
  }
}
``` 

UI должен это учитывать. Логику и тесты я переписал. Это позволит нам проводить апдейты широко спектра (через body = Object.assign({}, user, payload); и проверки на hasOwnProperty в валидаторе), но пока используем только для работы с description. Расширения нужно будет отражать в валидаторе, тогда как контроллер достаточно обобщен и в изменениях нуждаться не будет.

**Comment by dhilt** [comment]
@BitDen Обрати внимание, что в последнем тесте я затираю description, передавая не пустую строку, а "   ". При этом на контроллере не используются результаты работы валидатора. Это связано с тем, что payload является объектом (ссылочный тип переменной) и правки payload.description в валидаторе (а именно trim) отражаются в данных, на которые ссылается payload в контроллере.

**Comment by BitDen** [comment]
@dhilt Пока что сделал так, что есть эдакая одна админская страница с одной формой для изменения описания пользователя. Правда после прихода успешных данных с сервера не появляется алерт с надписью 'success', возможно это связано с тем, что fetch написан с помощью колбэка, а не промиса. И ввиду этого компонент не перерендеривается...
Далее нужно сделать функцию наподобие checkAuth, чтобы только админ мог заходить на админские роуты.
И сейчас доделаю наконец-то роут вида `translators/:name`.
И еще хотелось бы спросить почему удалили (https://github.com/dhilt/dharmadict/commit/a1adac10a0ed11b6869ff93a267ed345c0a923dd) в UpdateUserSpec попытку добавления несуществующего пользователя, вроде бы вполне полезный тест - если пройдет пользователь с несуществующим id, он попросту создаст свою запись в базе данных, будет одним пользователем больше, хотя метод update совсем о другом.

**Comment by BitDen** [comment]
@dhilt Страницы переводчиков обновил: https://github.com/dhilt/dharmadict/commit/771341f08bf41a0d1ebee71c9fc06d0ac56561fc

**Comment by BitDen** [comment]
@dhilt Касательно checkAuth и проверки на доступ к определенному роуту - может стоит поступить как в react-try, сделать вспомогательный компонент для проверки на роль? Пока что смутно представляю как в текущем коде написать что-то похожее на checkAuth, только для админа.

**Comment by dhilt** [comment]
@BitDen Во-первых, защита есть, это onEnter, который deprecated в следующей версии роутера. Но мы используем эту и onEnter={checkAuth} защищает роут от доступа простых смертных.

Далее, давай со страницей поступим так. У нас есть /translator/:login. Давай сделаем /translator/:login/edit. Если не выйдет такой роут, то можно наоборот /translator/edit/:login. Но лучше первый вариант. Этот роут защищен onEnter. Таким образом нам не нужно будет возиться в указанием id переводчика, поскольку id зашивается в адрес. 

И на этой странице выводим description в виде textarea. Остальные поля можно показать в режиме read-only, простым текстом. А можно сделать переключатель языка (русский, английский) через select-box или radio-button (второй вариант проще), а также редактирование имени через text-input. Если будешь делать доп. поля, нужно будет разрешить их на сервере. Это делается через валидатор (hasOwnProperty, trim для текстового ввода и жесткая проверка для языка).

Ссылку на новый роут нужно показывать на странице переводчика, но только админу.

**Comment by BitDen** [comment]
@dhilt Да, защита конечно была, да только она проверяла просто авторизированный пользователь или нет. А нам нужно было именно проверку на админа, вот вроде сделал: https://github.com/dhilt/dharmadict/commit/b63a1154525f4b8aada5bc2c861c8bf154ee4cc5

**Comment by BitDen** [comment]
@dhilt Сделал все как роут 'translator/:login/edit'. Только вот переменная в адресе означает ведь именно логин, а не id. Сейчас у существующих пользователей нам достаточно логин с помощью `.toUpperCase()` привести к виду id. Но вообще-то говоря ничего нам не гарантирует, что login и id это одни и те же строки, только с разным регистром.

И еще наверное соединять checkAuth и checkAdmin будет неразумно. У checkAdmin есть довольно солидная задержка, пока придет ответ с сервера.

**Comment by BitDen** [comment]
@dhilt Добавил возможности для изменения языка и имени: https://github.com/dhilt/dharmadict/commit/9a35d000fd7b5fdf70c82ddc32c38321b8417621
Правда выходит, что роут `/translator/:login/edit` может примениться к любому пользователю, не только с ролью переводчика. Может на старте этого компонента стоит проверять роль и показывать NotFound, если login не переводчика?

И я не уверен, что сработает следующий момент - https://github.com/dhilt/dharmadict/commit/9a35d000fd7b5fdf70c82ddc32c38321b8417621#diff-02a662a2ebf8c71be27dc495f2fd025aR17. Я бы даже сказал что полностью уверен что не сработает. Но проверить пока не могу, с работающим эластиком система наглухо виснет. Можно сказать написал коммит вслепую.

**Comment by BitDen** [comment]
componentDidMount как сейчас увидел, не помог. Пока не знаю, как бы выполнить команды вида dispatch(writeUserName(name)) после того, как закончится получение данных о пользователе. Может стоит попросту написать actions, который в случае отсутствия данных, которые должны были взяться на роуте `/translator/:login`, отправит сам запрос на сервер.

**Comment by BitDen** [comment]
@dhilt В общем не стал выдумывать с асинхронностью и просто сделал дополнительный action https://github.com/dhilt/dharmadict/commit/e32f5831be40af57659e6a16553ebb1fecf7d2e0.

**Comment by BitDen** [comment]
Сейчас еще решу проблему с id и login, просто один action стоит дописать.

**Comment by BitDen** [comment]
Готово: https://github.com/dhilt/dharmadict/commit/763e498467c7643bddc6a5e3161a75c96591d2e7

**Comment by BitDen** [comment]
@dhilt И тесты тоже добавил - https://github.com/dhilt/dharmadict/commit/95d1663e3e1d7f7deec8aec94b1e4380b5c45ffe. Задача пожалуй готова.

**Comment by dhilt** [comment]
@BitDen Сейчас если не засну, буду смотреть! постараюсь ответить на все вопросы или просто сделаю комит.

**Comment by BitDen** [comment]
@dhilt Да в общем-то вопросов уже нет, остается только посмотреть все ли качественно и правильно сделано.

**Comment by dhilt** [comment]
@BitDen 1) Я набросал checkAuth с параметром роли (https://github.com/dhilt/dharmadict/commit/fb5849c7f7ef96f5d1ad1d5f32f1db4c2fb60a33), сейчас не могу проверить из-за эластика, посмотри пожалуйста, должно работать в предположении, что на момент резолва auth.userInfo.promise в состоянии auth присутствует объект userInfo.

2) Положи NewTerm в /components/admin, раз уж ьам оказался EditUser. Так же еадо поступить со стором, загнать объект состояния newTerm внутрь admin.

3) Ты совершенно прав на счет разности id и login. И вот как надо поступить. Переведи роуты /translator/:login и /translator/:login/edit на /translator/:id и /translator/:id/edit. Соотв. в getTranslatorInfoAsync будет фигурировать id. API тоже нужно будет подправить. Выдавать логин в публичный доступ неправильно. Поскольку это упрощает работу по взлому аккаунта (из пары логин-пароль остается разобраться с одним паролем).

4) В state admin.changeUserData (во-первых переименуй его в admin.editUser) нужно выделить объект для редактируемых данных пользователя data: 

```
  admin: {
    editUser: {
      id: '',
      data: {
        name: '',
        language: '',
        description: '',
      },
      pending: false,
      result: null,
      error: null
    }
  }
```

Я вынес id. См. п.6.

5) Далее, мне понравилась попытка облегчить жизнь приложения за счет 

```
const {name} = this.props.initTranslatorInfo
    if (name === '') {
```

, но есть пара моментов. Первый: пользователь мог успеть перейти на редактирование до того, как загрузились данные с read-only страницы и тогда у нас будет 2 одинаковым запроса на сервер. Второй: данные могли устаретьна момент последнего посещения read-only страницы (именно поэтому, например, на TranslatorPage мы всегда запрашиваем данные на componentWillMount, игнорируя возможные повторные посещения). В общем, на нашей архитектуре (без обратной связи с сервером) запрос нужно делать всегда новый. 

6) Сделай id read-only на странице редактирования пользователя. Мы не можем так просто редактировать id перерводчиков. На них завязаны переводы терминов. Тем более, что id запрещен серверной валидацией.

7) Давай оставим 4 метода на классе EditUser, отвечающий за обработку инпутов. Но пусть все они вызывают 1 action updateUserData(data) (в продолжение концепции отдельного объекта для вводимых данных). Так же надо оставить один тип UPDATE_USER_DATA, пусть reducer ожидает объект data. На componentDidMount, например, вызов события мог бы выглядеть так: 

```
    dispatch(updateUserData({name, language, description}))
```

8) Почему мог бы? Потому что там вообще не должно быть логики пропихивания данных из одного state в другой. Меняем концепцию (во многом в соотв. с п.5), уточняем следующим ее образом. 

```
  admin: {
    editUser: {
      id: '',
      dataSource: {
        name: '',
        language: '',
        description: '',
      },
      data: {
        name: '',
        language: '',
        description: '',
      },
      pending: false,
      result: null,
      error: null
    }
  }
```

Здесь data связан с инпутами, а dataSource с исходными данными. Это требует разводки внутри getTranslatorInfoAsync. Добавь 2 параметр в getTranslatorInfoAsync, который будет определять куда пойдет результат. А результат у нас пойдет либо в translatorInfo.data, либо в admin.editUser.dataSource. Пусть бросаются 4 разных actions:

GET_TRANSLATOR_INFO_START
GET_TRANSLATOR_INFO_END
GET_ADMIN_USER_DATA_START
GET_ADMIN_USER_DATA_END

На reducer в случае GET_ADMIN_USER_DATA_END, обрати внимание, нужно класть в admin.editUser.dataSource только 3 поля, не весь ответ в отличии от ситуации с GET_TRANSLATOR_INFO_END и translatorInfo.data.

Когда с сервера приходит ответ на GET_ADMIN_USER_DATA_END, reducer должен положить его сразу в два места: в admin.editUser.dataSource и admin.editUser.data. Этим решается твой вопрос о синхронизации.

9) Добавь кнопку "Сброс". Обработчик бросает action, в котором в reducer уходит пара  RESET_ADMIN_USER_DATA (тип) и admin.editUser.dataSource (payload). И reducer перетирает admin.editUser.data в соотв.  с пришедшим payload.

**Comment by BitDen** [comment]
@dhilt 

1. Нет, не заработало. Вернул к прежнему варианту: https://github.com/dhilt/dharmadict/commit/54e332b05770a8bf96daa2d6cabcecddcfffed0a

2. https://github.com/dhilt/dharmadict/commit/5521c8dc228fb56df04eb50a982af2e8901c2e44

3. https://github.com/dhilt/dharmadict/commit/5823c5be6411d3813bb375a0d9114016546ab456

4. https://github.com/dhilt/dharmadict/commit/e680ef5b313ad41fb403b37e31e43e64d6391a59

5. https://github.com/dhilt/dharmadict/commit/456aa99dbffc21a64c35073f88bf57cb89dba79d

6. https://github.com/dhilt/dharmadict/commit/659348cca6f372934a464c345a2ea0407ff40c62

7-8. https://github.com/dhilt/dharmadict/commit/701c50dbf381b8c6fad714beb33616adfb3a9d50

9. Не совсем понял зачем множество action type вида RESET_ADMIN_USER_DATA_NAME, можно было бы просто кидать один action RESET_ADMIN_USER_DATA_ALL, который бы на reducer присваивал объект dataSource объекту data. Но сделал как описали: https://github.com/dhilt/dharmadict/commit/08abda7fe0b6ee681fa6902699b698890032bf6e

**Comment by BitDen** [comment]
@dhilt Еще предлагаю убрать state.admin.editUser.result. Нигде не используется, никакой смысловой нагрузки не несет. Об успешности загрузки данных можно попросту судить исходя из того, не равен ли state.admin.editUser.error объекту null.

**Comment by BitDen** [comment]
@dhilt И напоследок переписал роуты на компоненте About.
Может еще стоит сделать админский компонент для роута `/translator`? Там мог бы быть весь список пользователей (достающийся с помощью usersController.findAll).

**Comment by dhilt** [comment]
@BitDen RESET_ADMIN_USER_DATA должен был быть один, не понимаю, как ты увидел их 3. Тем не менее, я сделал небольшое review, в результате которого RESET_ADMIN_USER_DATA не осталось нисколько.

admin.editUser.result я убрал, но с этим пришлось убрать и success-оповещение. Тем более, что мне не нравится такая статика, я бы хотел увидеть там попап.

Вообще, посмотри, как я отрефакторил reducer. Я хочу чтобы на этом проекте вся логика была бы сосредоточена вне reducers. И там еще есть работа.

Весь список переводчиков пока не нужен, но нужно, чтобы заработали ссылки на переводчиков на странице поиска. Я создам отдельную задачу, включающую в себя этот момент.

**Comment by BitDen** [comment]
@dhilt Да, сам не знаю почему в фразе "RESET_ADMIN_USER_DATA (тип)" тип воспринял как приписку к константе в виде NAME и так далее, а не просто-напросто тип action'а.
Последний момент, связанный с логикой на reducers перенес - https://github.com/dhilt/dharmadict/commit/955fdc0def2b4ecd3416350259a18dfbcf4802dd.

**Comment by dhilt** [comment]
@BitDen Это отлично!
