### ISSUE TITLE
Server controllers

### ISSUE THREAD

**Issue by dhilt** [dhilt/dharmadict#8]
Запоздалая задача по рефакторингу контроллеров на сервере.

**Comment by dhilt** [comment]
@BitDen Последний комит на сегодня (https://github.com/dhilt/dharmadict/commit/0bfd67f41cb38eed4230200eb347d28c8808181d) посвящен рефакторингу GET /api/translation. Он еще не завершен, но теперь ясно, как это должно выглядеть с учетом doAuthorize и плоской цепочки then. 

Вынеси кусок с https://github.com/dhilt/dharmadict/blob/0bfd67f41cb38eed4230200eb347d28c8808181d/prod/server.js#L130 по https://github.com/dhilt/dharmadict/blob/0bfd67f41cb38eed4230200eb347d28c8808181d/prod/server.js#L150 (за исключением вызова res.json, конечно) в termsController.findTranslations. И метод getTermById загони в termsController.findById.

И продолжи эту работу для POST /api/update.

**Comment by BitDen** [comment]
@dhilt И я так понимаю помимо /api/translation, нужно создавать полноценный termControllers, вынося весь код связанный с terms с server.js?

**Comment by BitDen** [comment]
@dhilt Cделал как вы описали: https://github.com/dhilt/dharmadict/commit/17e71f130de4f46d3609f3d649f19d3441cc2b8a.
Но мне кажется метод findTranslations получился и запутанным, и не совсем отражающим свою суть. Может все-таки единственными параметрами у него должен быть translator (данные, найденные на /api/translation через `usersController.findByLogin(req.query.translatorId)`) и termId (req.query.termId)?

**Comment by BitDen** [comment]
@dhilt Сделал новый метод searchByPattern: https://github.com/dhilt/dharmadict/commit/0efa17c69a04d451f7b12327b54acd631f81fd34.
Следующие на подходе два метода - createTerm и updateTerm, и на этом пока что создание termsController закончится вроде. Далее надо будет пересмотреть все же findTranslations и в целом взглянуть на всю картину сервера.

**Comment by BitDen** [comment]
@dhilt Последние два метода готовы: https://github.com/dhilt/dharmadict/commit/1daf5ac9ebe3de5f9feed22c9fcc9a24080ec2dc и https://github.com/dhilt/dharmadict/commit/2705980c3834fe72c46d36b6e08dad2856295814.
Метод updateTerm слегка подкорретиковал - теперь id переводчика берется из объекта user, полученного после doAuthorize().

**Comment by BitDen** [comment]
И еще заметил что не хватает проверки роли на updateTerm - https://github.com/dhilt/dharmadict/commit/a82e773dfc83dff8e552f4f1c36d9f60010a10d5.

**Comment by dhilt** [comment]
@BitDen Я залил в бранч translator-page рефакториг метода create и тесты к newTerm API: newTermSpec.js. Посмотри пожалуйста, как оно все устроено, как я переписал метод, чтобы он отвечал всем требованиям

 - четковыделенная секция с валидацией/подготовкой  входных данных
 - 404, включающая в себя обработку ошибки поиска (через перепробрасывание throw error)
 - финальный (существенный) запрос, включающий в себя лог ошибки БД

И как в тестах я читаю каждое сообщение об ошибке.

Обрати внимание, что сейчас закомментирован тест на повторное создание. Это связано с тем, что по какой-то причине приходится ждать до секунды времени, прежде чем система полностью "завершит" предыдущую запись в БД. То есть я создал термин, и только через какое-то время запрос на создание того же термина не пройдет через проверку на 404. Попробуй поиграть с этим моментом, возможно нужно что-то сказать эластику или это специфика тестового окружения... Не хотелось бы навешивать таймеры (я уже повесил по таймеру на создание/удаление пользователей)...

**Comment by dhilt** [comment]
@BitDen Я создал отдельную задачу https://github.com/dhilt/dharmadict/issues/13. Эту закрываем.
