### ISSUE TITLE
ApiError

### ISSUE THREAD

**Issue by dhilt** [dhilt/dharmadict#9]
Я ввел объект ApiError, позволяющий работать одновременно с текстом ошибки и кодом. И к нему хелпер sendApiError, заменяющий по сути собой responseError.

Под него я отрефакторил метод PUT /api/newUser в части usersController.create.

Задача 
 - разобраться с принципом работы ApiError
 - отрефакторить остальные части PUT /api/newUser (doAuthorize, usersController.isAdmin)
 - отрефакторить все остальные api-методы

Во всех почти случаях пусть код будет 500 (умолчание), на авторизацию можно выдавать 302, когда что-то не найдено 404...

**Comment by BitDen** [comment]
@dhilt Везде расставил ApiError, responseError больше не используется на server.js. Возможно стоит этот метод с sendApiError?

**Comment by BitDen** [comment]
@dhilt И еще попутно попал в небольшую конфликтную ситуацию с коммитами. Написал код, готовился закоммитить, перед этим запулился, и вроде как всего в двух местах по строке различались версии кода, что-то вроде `throw new ApiError...` и `return new ApiError...`
Коммит: https://github.com/dhilt/dharmadict/commit/79dab7ac456493dfa6ccee452d6394790118102c

**Comment by dhilt** [comment]
@BitDen Есть проблемы в твоем последнем коде. Заберись с бранча translator-page, выполни npm install и запусти npm test. Я покрыл логин тестами и твой рефакторинг обнаруживает недостаток. Я поясню сразу: 

у тебя здесь throw https://github.com/dhilt/dharmadict/blob/79dab7ac456493dfa6ccee452d6394790118102c/prod/controllers/users.js#L17 

а здесь catch
https://github.com/dhilt/dharmadict/blob/79dab7ac456493dfa6ccee452d6394790118102c/prod/controllers/users.js#L29

Второе место ловит первое и затирает ошибку. Тест ожидает 'Invalid params', а получает 'Database error'.

**Comment by dhilt** [comment]
@BitDen Если этот метод уходит наружу, то давай считать, что catch будет снаружи (сейчас так и есть, см app.post('/api/login')). И я, если честно, вообще не понимаю, зачем там catch.

**Comment by BitDen** [comment]
@dhilt А я честно говоря и не помню даже чтобы catch пытался писать будучи на controllers. Мда уж, бывает, исправил: https://github.com/dhilt/dharmadict/commit/288b0d16d402c72c86989a1f75672e6a1de5a749

**Comment by BitDen** [comment]
@dhilt Так, а касательно самой задачи об ApiError - сливать методы responseError и ApiError?

**Comment by dhilt** [comment]
@BitDen Ты имеешь в виду sendApiError и responseError? Да, если responseError отдельно нигде не фигурирует, конечно, их надо слить. Лог выводи всегда через logger.error.

**Comment by BitDen** [comment]
@dhilt Да, точно, их. Сейчас солью и можно закрывать задачу.

**Comment by BitDen** [comment]
И да, responseError теперь нигде не появляется, на server.js на случай ошибки везде теперь один метод sendApiError.

**Comment by BitDen** [comment]
@dhilt Хотелось бы спросить, нормально что переменная logLevel теперь исчезнет? Я сколько не смотрел, нигде не видел такого применения.
```
let responseError = (res, message, status, logLevel = 'error') => {
  if (logLevel === 'error') {
    logger.error(message)
  } else {
    logger.info(message)
  }
  // res.statusCode = status ???
  res.send({
    error: true,
    message: message
  })
};
```

А метод убрал: https://github.com/dhilt/dharmadict/commit/72cc58ed4924e2836b5265b88161bfe4d766528c
